### ISSUE TITLE
支持android SDK 23的进度

### ISSUE THREAD

**Issue by dxsdyhm** [dxsdyhm/GwellDemo#1]

**Comment by liulei9385** [comment]
什么时候可以支持android sdk 23 以上呀，现在项目用到了，编译报错

**Comment by liulei9385** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.royalstar.smarthome.wifiapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.royalstar.smarthome.wifiapp-1/lib/arm, /data/app/com.royalstar.smarthome.wifiapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libSDL.so"

**Comment by dxsdyhm** [comment]
1.SDK 23的问题现在已经解决了，但是引发了SDL的一个功能性的BUG，最终解决的时间估计不会太久
2.不知道你们用23具体是为了使用那个部分而导致的问题

**Comment by chefil** [comment]
集成到项目一直报p2p call fail是怎么回事

**Comment by dxsdyhm** [comment]
有可能是P2PConnect并没有成功
1.这个方法有返回值，返回false是不可以使用P2P的所有方法的
2.记得在不需要P2P模块之后（建议在APP退出时）调用DisConnect

**Comment by dxsdyhm** [comment]
@chefil  有可能是监控一次之后返回，在没有再次登录的情况下再次监控导致的,因为这个Demo比较简单，所以Disconnect这个方法调用是直接在监控页销毁的时候，但这个做法是错的，下一版demo会改用一个与APP生命周期相同的服务来 管理 Connnect  与 Disconnect  
connect  P2P鉴权连接，成功之后才可使用P2P功能
disconnect   P2P断开连接，断开之后在没有再次connect之前P2P功能不可用

**Comment by dxsdyhm** [comment]
@liulei9385 0.2.7版本开始已经支持 Android SDK 23了，可以尝试一下

**Comment by 18359422169** [comment]
P2PConnect.connect报错，.so文件SDL文件找不到，lib用的是0.2.8版本的，我sdk22的

**Comment by dxsdyhm** [comment]
你确认一下编译出来的APK，里面只有 armeabi一个文件夹？
1.如果有多个，删除其他的，可能是由于你引用的其它库包含其它ABI的动态库导致的
2.如果只有一个 ，看一下里面有没有SDL这个库，（应该是有的）

**Comment by dxsdyhm** [comment]
暂时还是对23＋支持有问题，恢复到 0.2.6

**Comment by 18359422169** [comment]
我这边用只有发布防指令的时候，返回多个撤布防回调结果。SDK 0.2.8

**Comment by dxsdyhm** [comment]
由于更换了编译工具，SDK 0.2.7与0.2.8都出现了一个BUG，暂时先用0.2.6
BUG已经找到，今天会更新上去，

**Comment by dxsdyhm** [comment]
重新上传了0.3.1版本
