### ISSUE TITLE
可以针对监控回来的影像进行处理吗?

### ISSUE THREAD

**Issue by jamesweb1** [dxsdyhm/GwellDemo#100]
我的应用不只是单纯做监控
希望实时取得NV21的影像做其它处理
目前看到P2PListener里面没有这个callback
假设可以达到30fps, 那我希望每秒可以拿到这30个byte[] imageNV21
不知道是否可行?

**Comment by dxsdyhm** [comment]
可以参考这个接口
```java
    /**
     * 设备传过来的,解码前的音视频数据,已停止回调
     * @param AudioBuffer 音频数据
     * @param AudioLen 音频长度
     * @param AudioFrames 音频帧
     * @param AudioPTS 音频PTS
     * @param VideoBuffer 视频数据
     * @param VideoLen 视频长度
     * @param VideoPTS 视频PTS
     */
    @Override
    public void vRecvAudioVideoData(byte[] AudioBuffer, int AudioLen, int AudioFrames, long AudioPTS, byte[] VideoBuffer, int VideoLen, long VideoPTS) {
    //1.这个回调有个开关，默认是不会回调的（影响性能）
    //2.有了本地录像功能后，这个回调被关闭了
    //3.原始H264格式，不是很建议做这个处理，如果确实需要，可以将此接口放开 
    }
```

**Comment by jamesweb1** [comment]
我目前没有使用本地录像功能, 这个函数似乎一样没有被回调...
您说的开关在哪边? 看了文件没有找到类似的函式

**Comment by jamesweb1** [comment]
我剛才有找到這個
`P2PHandler.getInstance().setRecvAVDataEnable(true);`

但是設置後在vRecvAudioVideoData印字串仍然沒有回調的跡象...

**Comment by dxsdyhm** [comment]
@jamesweb1 对，以前这个方法就是控制上传音视频数据的开关，现在加了内部本地录制之后就关了

**Comment by dxsdyhm** [comment]
@jamesweb1 如果没有特别需求，原计划是不准备打开的

**Comment by jamesweb1** [comment]
所以我现在有什么办法打开这个回调吗?
我必须利用p2p传送回来的视频做其他的应用, 比如人脸识别, 将侦测到的人脸重送至后台等等。

**Comment by dxsdyhm** [comment]
@jamesweb1 1.需要更新SDK才可以打开（可能需要一点时间）

**Comment by jamesweb1** [comment]
好的, 那再等SDK的更新了, 不然有这个回调却没有作用也是挺奇怪的。希望能尽快地好, 哈~

**Comment by jamesweb1** [comment]
请问这个功能, 有预计完成的时间吗？

**Comment by dxsdyhm** [comment]
@jamesweb1 尽量在本周吧

**Comment by dxsdyhm** [comment]
@jamesweb1 下班前应该可以提供
