### ISSUE TITLE
网络请求失败

### ISSUE THREAD

**Issue by clanaid** [dxsdyhm/GwellDemo#104]
SSL handshake timed out

**Comment by clanaid** [comment]
请求验证账号这个接口现在报HTTP 500错误

**Comment by dxsdyhm** [comment]
@clanaid 是指这个接口```checkAccountExist```?

**Comment by clanaid** [comment]
对

**Comment by dxsdyhm** [comment]
@clanaid 现在还是长期必现的么？我测试了好像能够正常返回吧？

**Comment by clanaid** [comment]
现在还会，我这个项目的sdk还是rx1的版本，这个有关系吗

**Comment by clanaid** [comment]
今天能解决下吗

**Comment by dxsdyhm** [comment]
@clanaid 这个，这边没有复现问题
理论上rx 版本不会引起这样的差异，还是建议你升级SDK试试（如果可行的话）

**Comment by penchen520** [comment]
第三方注册   onErrorfailed to connect to api2.cloudlinks.cn/120.79.215.131 (port 443) after 10000ms  现在非常容易失败。。。

**Comment by penchen520** [comment]
第三方注册 onErrorfailed to connect to api2.cloudlinks.cn/120.79.215.131 (port 443) after 10000ms 现在非常容易失败。。。
 onErrorSSL handshake timed out

**Comment by dxsdyhm** [comment]
@clanaid #106

**Comment by clanaid** [comment]
@dxsdyhm 是要升级版本才能解决吗

**Comment by dxsdyhm** [comment]
@clanaid 升级并不保证一定解决问题，但如果升级成本不高的话，建议升级
因为内部请求封装的是Retrofit 可能它有一些优化，这个异常网上也有资料，感觉都没什么特别有价值的解决办法，感觉是加密通信耗时更长，估计导致了超时

**Comment by clanaid** [comment]
升级后还是一样，你们的接口现在是响应500错误

**Comment by clanaid** [comment]
是这个接口废弃了吗
![image](https://user-images.githubusercontent.com/7777205/42035965-bcc4a33c-7b16-11e8-9640-9486517d2c07.png)

**Comment by dxsdyhm** [comment]
@clanaid 我用的```0.4.4```版本测试的
![](http://7xp6ld.com1.z0.glb.clouddn.com/EDA57D9D-2C4A-4144-ACBF-CFEC0058B627.png)
你能发一下这一次请求的详细日志么？

**Comment by clanaid** [comment]
查了下，这个接口检查手机现在是不需要国码了吗，因为之前都是带国码没报错过的，现在一带国码就会有问题了

**Comment by dxsdyhm** [comment]
@clanaid 这个问题暂时定位到问题了

1. 接口参数不带国码后台会默认为+86，所以支持不带国码查询，但不建议这么用
2. 之前的SSL异常是后台证书问题，这个问题已经解决并发布了
3. 这个查询接口我们下午尝试解决，并尽快发布

谢谢反馈！

**Comment by dxsdyhm** [comment]
@clanaid 接口现在应该已经正常了，你试试，有问题及时反馈

**Comment by clanaid** [comment]
好的

**Comment by clanaid** [comment]
对了，如果p2pConnect启动失败了，是不断重新启动连接吗？启动失败的原因可能是什么导致的

**Comment by dxsdyhm** [comment]
@clanaid P2PConnect这个的返回值不是指APP与服务器的连接状态，仅仅代表这个函数执行（代码层面）是否正常
也就是说，理论上没有概率返回false,如果存在，则可能是传入参数格式不正确，或库编译有问题或者之前已经连接了这些问题
所以启动失败基本上不需要重新启动连接，直接提示用户吧，代码上可以插入关键日志
