### ISSUE TITLE
使用DemoAPK上的功能需要申请key和id，编号吗？

### ISSUE THREAD

**Issue by ydajiang** [dxsdyhm/GwellDemo#105]
我手机和设备都在同意局域网内，但是Demo上一直都搜索不到设备，请问是没有APP唯一编号(00.00 由技威分配)这个的原因吗？

**Comment by dxsdyhm** [comment]
@yangjiechina 应该不是，局域网搜索失败，怀疑```我手机和设备都在同意局域网内```这个前提
排查：登陆**路由器**管理页面，查看已连接的设备中是否包含**手机**与**摄像头**

**Comment by ydajiang** [comment]
"设备体检"能够搜索到设备。"监控"页面输入id和密码，点击监控提示“监控挂断reson:0,code1:0,code2:0”。密码qwe123和用ipcTest上读取到的密码123都是这样。

**Comment by ydajiang** [comment]
是不是密码不对的原因？我这个设备还没有出厂，摄像机外壳包装也没有全是电路板，也没有说明书，不知道默认密码是多少。

**Comment by ydajiang** [comment]
123,6个8试了都不行。

**Comment by dxsdyhm** [comment]
@yangjiechina 这个，默认密码的问题差异比较大，有的设备还有可能默认空密码的，详细信息应该找给你设备的人询问密码，SDK中 reson:0  是密码错误的意思

**Comment by ydajiang** [comment]
好谢谢
