### ISSUE TITLE
第三方登录中 现在要失败3到4次才能成功

### ISSUE THREAD

**Issue by pengchen520** [dxsdyhm/GwellDemo#106]
调用        HttpSend.getInstance().ThirdLogin("3", VideoUtil.getIMEI(context), VideoUtil.getIMEI(context), PWD, "0", "2", subscriberListener);  调用的这个

异常  （code 是 998）
 onErrorfailed to connect to api2.cloudlinks.cn/120.79.215.131 (port 443) after 10000ms
或者 
onErrorSSL handshake timed out

**Comment by dxsdyhm** [comment]
@penchen520 好像解决方案一般都是延长超时时间，或者catch住这个异常，并重试，我们再看看
不过SDK内部是有重试的

**Comment by pengchen520** [comment]
关键是之前没有这种问题的， 没有这么高的失败率，貌似最近才出现的。

**Comment by pengchen520** [comment]
怎么延长超时时间， 貌似被封装了吧。

**Comment by dxsdyhm** [comment]
@penchen520 是被封装了，内部修改，这个问题我们再排查一下再说

**Comment by dxsdyhm** [comment]
@penchen520 你用的SDK 版本是多少？

**Comment by penchen520** [comment]
0.4.3

**Comment by pengchen520** [comment]
@dxsdyhm   0.4.3

**Comment by dxsdyhm** [comment]
@penchen520 用0.4.4试试吧

**Comment by dxsdyhm** [comment]
@penchen520 后台多服务器运行的过程中，证书不匹配，导致这个异常，现在已经解决并发布了
如果还有异常，可以反馈
