### ISSUE TITLE
长时间使用下, 会不定时断线

### ISSUE THREAD

**Issue by jamesweb1** [dxsdyhm/GwellDemo#107]
平台: Android
SDK版本: 0.4.4_2
装置: Galaxy S9

目前使用demo app测试, 发现连线后可看到画面, 但是放置一段时间后会自行断线(监控挂断), 大约是几个小时以后。现在尝试挂断后自动重新拨打, 发现讯息如下:

06-25 22:37:02.686 E/MonitorActivity( 5298):  监控挂断(reson:10,code1:806363139,code2:0)
06-25 22:37:03.508 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:03.698 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:03.918 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:04.129 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:04.338 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:04.368 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:04.598 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:04.818 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:05.038 E/MonitorActivity( 5298):  监控挂断(reson:1,code1:806363137,code2:0)
06-25 22:37:06.351 E/dxsTest ( 5298): 监控数据接收: ********

先是系统自动挂断, 然后重新拨打一直忙线中, 最后自动恢复了。知道为什么会自动挂断吗?有没有更好的解决方法？

**Comment by dxsdyhm** [comment]
@jamesweb1 

- **监控时一段时间内(10s 具体值差异不大)没有收到设备的握手包（2s一次），手机就认为设备“超时”，本次通话结束**，基于你监控几个小时的实际情况，极有可能是网络问题
- 设备忙线，是设备返回的信息，可能的原因是设备内存不足或者监控人数达到上限（一般是5）
- 针对你这样编码，不知道是仅仅作为测试还是业务需求，不建议做成长时间监控的场景，监控上限很容易就超出了

解决办法，APP应该没有什么特别可做的吧，优化的话：不要短时间内多次发起呼叫（也就是挂断立马呼叫），间隔时间可以递延也可以固定间隔
