### ISSUE TITLE
门铃按呼叫按钮后android/ios app接收不到的概率很大

### ISSUE THREAD

**Issue by foreverGoUp** [dxsdyhm/GwellDemo#108]
环境：android sdk----------com.p2p.core:p2p-core:0.3.8
![qq 20180703201313](https://user-images.githubusercontent.com/20222580/42219173-8861c788-7efd-11e8-9b75-f3833c933836.jpg)

5台手机：5个不同的账号登录2台android/3台苹果。应用都在前台显示且不息屏。
测试步骤：隔一分钟按一次门铃呼叫按钮
结果：总有1-3台收不到门铃呼叫

1、请问最近门铃服务不稳定了吗？再这样下去我们公司计划弃用门铃这个设备了。
2、ios的门铃呼叫如何使当应用在后台时也能正常接收？

**Comment by dxsdyhm** [comment]
@foreverGoUp 
*  ```总有1-3台收不到门铃呼叫```:是固定某些，还是随机概率？5个账号是否都在设备的报警推送列表中？
*  ```门铃服务不稳定了吗```:门铃没有单独的业务逻辑，共用的P2P指令，你可以在门铃推送的出口（Android有透传和报警两种可能，不清楚你们的门铃是走哪个通道）打印日志，测试结果以日志为准，至于界面稍后再排查
*  ```ios的门铃呼叫如何使当应用在后台时也能正常接收```:不知道这个在后台是指APP存活还是指离线，我们的门铃呼叫（报警消息的一类）支持iOS的离线推送，其他问题基本都是技术问题，可以参考iOS的文档或者询问iOS的技术支持

**Comment by foreverGoUp** [comment]
@dxsdyhm 现在正常了。30分钟前以及之前都不正常，5台手机随机几台收不到门铃呼叫推送。感觉这个门铃呼叫推送就是不太稳定，能说一下这个推送机制和过程吗？

ios的门铃呼叫如何使当应用在后台时也能正常接收:ios刚退到后台，应该是App存活，那么门铃呼叫还会像应用在前台显示时从sdk进入吗（不是通过走苹果服务器）？

**Comment by dxsdyhm** [comment]
@foreverGoUp 

- 在线推送是P2P完成的，也就是设备与手机都与P2P服务器有心跳连接，和普通P2P指令相同的链路过程，只不过不同的是路径方向是反向的（设备发起，指令到达手机端），报警ID列表就是设备要发的指令目标集合，在上面的ID都会发门铃有人来访指令，如果测试调节与观察结果没有误差，也可能是网络问题（双端与服务端）
- APP存活的话，应该是可以从SDK进入的，权威答案还是要iOS的开发人员给出
- 如果任然觉得有问题，可以提交反馈到贵公司与我司的联络人，会安排多端一起排查，这里只能解决Android SDK开发相关的问题
