### ISSUE TITLE
如何多台手机同时呼叫同一个摄像头?

### ISSUE THREAD

**Issue by jamesweb1** [dxsdyhm/GwellDemo#109]
我用SDK可以呼叫一个摄像头并且观看到画面

但是当第一台持续连线, 第二台要播打(call)进去的时候

就会出现以下信息:

监控挂断(reson:1,code1:806363137,code2:0)

看reson的意思是对方忙线中

现在SDK不支援多个手机同时观看画面吗?

**Comment by dxsdyhm** [comment]
@jamesweb1 支持的，取决于设备端的配置以及设备的资源消耗
配置还好说，原版设备上限是5，不知道你们的设备端程序是否有修改
确实忙线的话，可能是设备资源不足，无法满足下一个用户连接，如果大量设备以及大概率出现的话可以提交问题到对接人反馈一下问题，短时小概率出现的话可以认为是正常现象
还有一点，注意到你的描述中有持续连线，是不是意味着不长时连线就可以多人观看了？

**Comment by jamesweb1** [comment]
您好, 我使用官方Yoosee的软件, 可以同时在两个不同的装置观看摄像头。
但是使用Gwell的SDK拨打就会出现上面的错误讯息, 因此猜测是拨打方式错误, 我参考demo的拨打方式连线的, 方式如下:

```
P2PHandler.getInstance().call(userId, pwd, true, 1, callID, "", "", 1, callID);
```

还是说官方提供的SDK不支持多个手机连入设备?

**Comment by dxsdyhm** [comment]
@jamesweb1 拨打方式没有错误
1. SDK与Yoosee的代码是同源的，SDK仅仅有可能落后于Yoosee的发布版,但不会有多版本差异（SDK发布与否与二次开发的需要程度相关）
2. 测试时不应该使用相同的账号登陆
3. 如果测试结论比较稳定的话，可以约个时间，使设备在线，我们这边安排人员通过Demo远程测试一下看看现象（不要在Github中暴露测试信息，可通过公司联络人说明情况即可（这个测试应该不会持续很长时间））
