### ISSUE TITLE
获取验证码报错10901050，提示APPID，Token不正确，请问APPID，Token该如何申请？

### ISSUE THREAD

**Issue by dcl1994** [dxsdyhm/GwellDemo#11]
public static MyApplication app;
    //这三个参数需要服务器分配(ID token与版本(在同一版本)是固定的,可硬编码在代码中。版本迭代时需要修改版本)
    //连接时需要传入，下面的数据仅供测试使用

    public final static String APPID="1e9a2c3ead108413e8218a639c540e44";
    public final static String APPToken="7db7b2bff80a025a3dad546a4d5a6c3ee545568d4e0ce9609c0585c71c287d08";

    //前两位是客户APP唯一编号(00.00 由技威分配),后两位是APP版本号(客户自定义),此参数不可省略
    public final static String APPVersion="00.00.00.01";

**Comment by dxsdyhm** [comment]
需要与我们技术支持联系，会让提供一个表格，填好之后会回复这些信息

**Comment by dcl1994** [comment]
能提供个技术人员的联系账号么？

**Comment by dxsdyhm** [comment]
查看[issuse #9 ](https://github.com/dxsdyhm/GwellDemo/issues/9)
