### ISSUE TITLE
Android端回放视频时，如何监听进度

### ISSUE THREAD

**Issue by afjzwed** [dxsdyhm/GwellDemo#110]
Android端使用以下方法 P2PHandler.getInstance().playbackConnect(java.lang.String contactId,java.lang.String password, java.lang.String filename,int recordFilePosition,int VideoMode,int subtype,int videow, int videoh,int fishPos); 回放视频可以成功，但是不能快进，文档上建议用“MadiaPlay.iRecFilePlayingControl 第一个参数填4  P2pHandle.getInstance.vRetPlayBackPos”来做进度条监听，可是我的sdk中并没有vRetPlayBackPos这个方法，我的sdk版本是0.3.8，是版本太旧没有这个方法，还是说应该用另一个别的方法？？

**Comment by dxsdyhm** [comment]
@afjzwed ```P2PListner```里面有接口回调（这是IP2P的实现类），SDK每个版本都有，播放的过程中自动回调，不需要调用某个接口获取，不知道你看的文档地址是哪里，我看一下写的是不是有误？

**Comment by afjzwed** [comment]
文档地址[http://doc.cloud-links.net/SDK/Android/FAQ/FAQ.html](http://doc.cloud-links.net/SDK/Android/FAQ/FAQ.html)，第11个问题

**Comment by dxsdyhm** [comment]
@afjzwed ```P2PListner```里面的```vRetPlayBackPos```可以用来做进度条，监控过程中自动回调，文档会做修改，对于快进，最好按照文档的说法，使用拖动进度条来实现（SDK支持回放seek），谢谢反馈。
