### ISSUE TITLE
调用第三方注册没有响应

### ISSUE THREAD

**Issue by pengchen520** [dxsdyhm/GwellDemo#113]
调用第三方注册没有响应

**Comment by dxsdyhm** [comment]
@penchen520 提供一下接口调用信息，以及回调日志之类的有用信息

**Comment by pengchen520** [comment]
HttpSend.getInstance().ThirdLogin("3", VideoUtil.getIMEI(context), VideoUtil.getIMEI(context), PWD, "0", "2", subscriberListener);

**Comment by pengchen520** [comment]
没响应回来，也没报错把

**Comment by dxsdyhm** [comment]
@penchen520 不可能没有反应的，要不然你把操作前后的**所有**日志都贴出来，不然很难排查问题

**Comment by pengchen520** [comment]
今天好了，这个第三方注册最近都不稳定
