### ISSUE TITLE
新摄像头 使用声波配网后 密码怎么处理 

### ISSUE THREAD

**Issue by pengchen520** [dxsdyhm/GwellDemo#114]
现在用默认密码123 ，会提示密码错误。 看到官方app 在声波配网成功后 ，把 设置密码去掉了。

**Comment by dxsdyhm** [comment]
@penchen520 官方APP对于新的摄像头添加，最终都是由程序生成密码传给设备，这种设计执行前分两种情况  
1. 有默认密码（配网设备返回的数据里面有标识），引导用户输入默认密码，并程序内部调用修改密码指令修改为随机密码
2. 没有默认密码，直接调用设置初始密码指令，设置随机密码

**Comment by dxsdyhm** [comment]
@penchen520 当然你也可以选择不采用这个方案，与官方相比密码仅仅是由随机生成改成了由用户输入（PS:每类摄像头（不同批次，不同厂家）默认密码不尽相同，最好不要认为默认密码是某一个初始密码）

**Comment by clanaid** [comment]
@dxsdyhm oppo手机总有客户说连接不上，你们有解决的方法吗

**Comment by clanaid** [comment]
@dxsdyhm 还有连接的问题应该不关这个sdk时吧，我这个app用的版本是0.4.3,我看0.4.4只是升级了rxjava2而已吧

**Comment by dxsdyhm** [comment]
@clanaid 
* 1.你们可以先排查一下非网络原因，比如，你们可以用其他手机尝试连接一下客户的设备（如果不想提供密码，可让客户配合尝试其他手机）
* 2.连接问题服务器一直有在优化，如果客户端测试稳定之后也会放出P2P的升级优化版本
* 3.连接问题只能说有一半和SDK相关，还有一半需要排查客户环境，可能是样本误差
