### ISSUE TITLE
AP配网

### ISSUE THREAD

**Issue by clanaid** [dxsdyhm/GwellDemo#118]
AP配网，设备收到ssid并开始连接时，app端连回正常的wifi并开始监听，需要发什么命令给摄像头的吗，不发指令过去好像不会收到摄像头返回来的信息，我现在是发{0, 1, 1, 1}过去，返回来的信息解出来不对

**Comment by clanaid** [comment]
![image](https://user-images.githubusercontent.com/7777205/43389730-03cb13a8-941f-11e8-97b4-82e5a95752fb.png)

**Comment by fangxiaole** [comment]
不用发送命令给摄像头，只需要通过UDP监听9988端口返回的信息

**Comment by clanaid** [comment]
请问下设备同步的问题，sdk能拉取你们在app添加的设备回来吗，secretKey加密的密码如何解，SDK中P2PHandler.getInstance().HTTPDecrypt（）该方法也需要传入一个密码

**Comment by dxsdyhm** [comment]
1.能拉取已经同步过的设备
2.服务器拉取回来的密码作为入参解密，```P2PHandler.getInstance().HTTPDecrypt（）```返回值就是解密后的密码
