### ISSUE TITLE
so文件找不到  工程作为一个library

### ISSUE THREAD

**Issue by woshiqinwei** [dxsdyhm/GwellDemo#119]
SDL.so找不到

**Comment by dxsdyhm** [comment]
@woshiqinwei 这个工程师一个Application   不要直接作为library,gradle导入p2p-core，将工程的SDK目录文件复制进主工程就可以了
* 强行使用的话  你试试
```gradle
repositories {
    flatDir {
        dirs 'libs'
    }
}
```
或者将库引入改为主工程引入

**Comment by woshiqinwei** [comment]
将so包放到armeabi v7和armeabi包是否可行

**Comment by dxsdyhm** [comment]
@woshiqinwei 你最好还是用SDK的方式引入（gradle）
