### ISSUE TITLE
这两个验证验证码的接口有什么区别吗？还有鉴权验证码是自己填写？给个demo吧 T T，这里有点不是很清楚

### ISSUE THREAD

**Issue by dcl1994** [dxsdyhm/GwellDemo#12]
/**
     * 验证手机验证码
     * @param ID 账户ID
     * @param VKey 鉴权验证码（通过获取验证码接口获）
     * @param CountryCode 国码 eg:86 （暂不支持非大陆手机号）
     * @param PhoneNO 手机号码
     * @param PhoneVerifyCode 手机验证码（通过获取手机验证码接口获取，验证码通过短信发至手机）
     * @see HttpSend#getPhoneCode(String, String, SubscriberListener)
     * @param subscriberListener 验证手机验证码的回调
     */
    public void getCheckPhoneVKey(String ID, String VKey, String CountryCode, String PhoneNO,
                                  String PhoneVerifyCode, SubscriberListener subscriberListener) {
        HttpMethods.getInstance().getCheckPhoneVKey(ID,VKey,CountryCode,PhoneNO,PhoneVerifyCode,subscriberListener);
    }

  /**
     * 验证手机验证码
     * @param CountryCode 国码 eg:86（暂不支持非大陆手机号）
     * @param PhoneNO 手机号
     * @param VerifyCode 手机验证码（通过获取手机验证码接口获取，验证码通过短信发至手机）
     * @see HttpSend#getPhoneCode(String, String, SubscriberListener)
     * @param subscriberListener 验证手机验证码的回调
     */
    public void verifyPhoneCode(String CountryCode, String PhoneNO, String VerifyCode,
                                SubscriberListener subscriberListener) {
        HttpMethods.getInstance().verifyPhoneCode(CountryCode,PhoneNO,VerifyCode,subscriberListener);
    }

**Comment by dxsdyhm** [comment]
使用场景不同，带账户ID参数的那个接口是```修改账户密码```或者```手机号找回密码```的时候使用
   而不带账户ID的接口是```大陆手机号注册```的时候使用
