### ISSUE TITLE
SDK自9/26起无法拨打成功

### ISSUE THREAD

**Issue by jamesweb1** [dxsdyhm/GwellDemo#120]
前一段时间我们在开发中都可以正常拨打成功, 但是今日开始用您的SDK就一直"监控挂断”。相关的信息如下：

09-26 11:26:12.186 29286-29286/com.gwelldemo E/Gview: fgP2PCall
09-26 11:26:12.186 29286-29286/com.gwelldemo I/tag: p2p call success
09-26 11:26:12.688 29286-29295/com.gwelldemo I/zygote: Compiler allocated 4MB to compile void android.view.ViewRootImpl.performTraversals()
09-26 11:26:16.402 29286-29472/com.gwelldemo E/sdk.P2PListener: sdk.P2PListener
09-26 11:26:16.421 29286-29286/com.gwelldemo E/MonitorActivity: P2P_REJECT: 监控挂断(reson:10,code1:806363140,code2:0)

已经尝试过reset摄影机以及连接到不同的WiFi环境, 都得到一样P2P_REJECT的结果...尝试用官方Yoosee App则可以正常观看。请问要怎么解决这个问题? 恳请进排除这个issue, 谢谢。

ps. 我的版本是implementation 'com.p2p.core:p2p-core:0.4.4_2’ (含有回传接收影像的需求: vRecvAudioVideoData)

**Comment by jamesweb1** [comment]
这两天经过多次尝试, 发现这个现象发生在SDK版本0.4.4_2 (也就是特制版)

重现的步骤就是分别由两台手机轮流拨打同一个摄像头, 其中一支手机就会出现reson:10,code1:806363140,code2:0

可否帮忙更新SDK但是需要有接收影像的功能

也就是下面这一段: 

 /**
     * 开始获取音视频流
     * 须正常监控，有音视频流传入时才可使用
     */
P2PHandler.getInstance().startGetAudioVideoData();

/**
     * 音视频流数据
     * @param AudioBuffer  音频数据  格式（AMR）
     * @param AudioLen  音频数据长度
     * @param AudioFrames 音频帧
     * @param AudioPTS  pts
     * @param VideoBuffer 视频数据  格式（h264）
     * @param VideoLen  视频数据长度
     * @param VideoPTS  pts
     */
    void vRecvAudioVideoData(byte[] AudioBuffer, int AudioLen, int AudioFrames, long AudioPTS,
                             byte[] VideoBuffer, int VideoLen, long VideoPTS);

 /**
     * 停止获取音视频流
     * 
     */
P2PHandler.getInstance().stopGetAudioVideoData();

谢谢。

**Comment by dxsdyhm** [comment]
@jamesweb1 有人在看这个情况，如果有发现，会联系的

**Comment by jamesweb1** [comment]
@dxsdyhm 另外, 我发现当其中一支手机正在观看画面, 另外一个手机也用相同帐号登入, 第一支手机就会被挂断。 然后第一支手机除非重新登入, 否则无法再拨打成功...

看到的打印信息(第一支手机)如下:
10-08 14:59:09.281 2472-2689/com.gwelldemo D/2cu: vRetLoginAnother: MediaPlayer

请问同时间只能一支手机登入, 是本来的限制吗?

**Comment by dxsdyhm** [comment]
@jamesweb1 同一个账号只能在一个手机上登陆，但是允许不同账号同时观看摄像头画面

**Comment by jamesweb1** [comment]
请问, SDK的哪一个callback可以知道现在有人用相同帐号登入? 我看Yoosee有做到另一支手机登入就会提示登出。

**Comment by dxsdyhm** [comment]
@jamesweb1 登出是web 功能，http的错误码中有sessionid错误或者过期这个错误码，http请求遇到这样的错误码的时候就提示登出了
2.p2p接口也有踢飞接口，不过之前关闭了，

**Comment by jamesweb1** [comment]
请问, 所以现在在Android App中, 有办法做到感知此帐号目前已在其他装置中登入吗? 如果可以, 方法是什么哪?

**Comment by jwkj** [comment]
目前只能通过web接口监听的方式实现，当当前账号在其他地方登陆成功以后，你在该设备上再随意调用任何一个web接口，会返回一个状态码：30104006（android），20104006（iOS）；这个时候就代表在其他地方登陆了

**Comment by jwkj** [comment]
web http返回的错误码是String类型的，至于p2p接口我们后期会新增一个接口，你们被动监听就可以了，当账号在其他地方调用就会回调该方法：ISetting#void vRetLoginAnother(int LoginStatus);     这个方法的LoginStatus值为1的时候表示在其他的地方登陆了，目前SDK版本还未开放这个回调，你们可以先处理，后期升级SDK以后这个方法会生效
