### ISSUE TITLE
你们有h5版对接的吗？

### ISSUE THREAD

**Issue by clanaid** [dxsdyhm/GwellDemo#121]

**Comment by dxsdyhm** [comment]
@clanaid 你是说P2P指令在网页上发送和接收？

**Comment by clanaid** [comment]
网页应该不支持p2p吧，有没直播流可以直接通过web端看的

**Comment by dxsdyhm** [comment]
新出的增值服务可以在web端查看，是m3u8,但延迟比较大，不适合监控，可以做回放，达到现在p2p效果的web端还不可以（一般延迟都会比较大，或者需要大量资源），局域网支持rtsp。总得来说你想达到的结果现在应该还不支持
