### ISSUE TITLE
v7a so

### ISSUE THREAD

**Issue by StoneXL** [dxsdyhm/GwellDemo#122]
怎么支持v7a 按照解压复制aemeabi中的so到v7a下 还是奔溃报错 我用的是0.3.8  
![default](https://user-images.githubusercontent.com/18682525/51832105-bbef4a00-232e-11e9-9b8e-ea217444dcf7.png)

**Comment by dxsdyhm** [comment]
0.3.8版本打包出apk 后，在lib里面找对应的三个（参考文档）so  复制到主工程的v7a目录下
如果有问题，建议有条件的还是降级使用armeabi的，后面会尽快编译出v7a的版本

**Comment by StoneXL** [comment]
能说下具体是哪几个so么

**Comment by StoneXL** [comment]
如果我armeabi和v7a目录都要该怎么放

**Comment by StoneXL** [comment]
还要加arm64-v8a的so该怎么破 加下qq2823466341

**Comment by StoneXL** [comment]
qq282346341

**Comment by dxsdyhm** [comment]
* 三个库**mediaplayer**   **sdl**   **mp4v2**
* arm64 暂时不支持，so不需要支持那么多，一般保留armv7a就行了
* 如果要保留v7a和arm gradle配置成支持两个就可以了，然后将三个库复制到主工程v7a目录下（这个库本身就支持armeabi）
