### ISSUE TITLE
紧急求助，10901072   您的IP调用接口太频繁，已被限制访问 ，帮忙解决

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#127]
因为登录不成功，所以一直尝试登录导致死循环变成了错误10901072，IP调用接口太频繁已被限制访问
Ip地址是49.85.241.104。现在死循环已修改，帮忙解除限制，非常紧急。谢谢。

**Comment by dxsdyhm** [comment]
@haira1987 应该是会自动解封的
