### ISSUE TITLE
 监控挂断(reson:10)后再也连接不上监控，是否需要重新调用 P2PHandler.getInstance().p2pConnect

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#128]
监控挂断(reson:10)后再也连接不上监控，是否需要重新调用 P2PHandler.getInstance().p2pConnect

**Comment by dxsdyhm** [comment]
@haira1987 不需要，```reson10``` 检查一下设备和手机的网络是否正常
* 可以使用你们的app 看设置类的消息是否正常
* 或者异常时使用公版app查看监控或者设置消息是否正常
