### ISSUE TITLE
门铃推送，一个账号，多台android 设备，只有一个android 设备能接收到，需要什么设置吗

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#129]
门铃推送，一个账号，多台android 设备，只有一个android 设备能接收到，需要什么设置吗

**Comment by haira1987** [comment]
用KBell App,有时候也接收不到门铃的推送

**Comment by dxsdyhm** [comment]
@haira1987 
用户需要将自己的账号设置到设备的推送列表中，当有推送需求时，设备会遍历推送列表一个一个地推送消息，不知道你说地一个账号是什么意思，如果是一个用户账号的话，那一个android收到是正常的，另外一个用户账号不能在多个手机登陆，会相互踢飞，仅有一个可用
