### ISSUE TITLE
一些错误希望能帮忙解决

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#25]
demo版本    versionCode 1     versionName "00.00.00.01"
1.原demo中截图功能，报错直接退出。
2.原demo中，登录正常，但融合到本公司项目中，出现错误，错误代码20000，希望能提供各错误代码含义。
3.用demo的com.p2p.core.P2PView融合到本公司项目中报错，直接退出，找不出错在哪，即使全部复制demo中的activity_monitoer.xml也报错。

本公司项目配置android Studio2.3.2
 compileSdkVersion 25
    buildToolsVersion '25.0.1'
    aaptOptions.cruncherEnabled = false
    aaptOptions.useNewCruncher = false
    defaultConfig {
        applicationId 'com.or_home'
        minSdkVersion 18
        targetSdkVersion 23
        versionCode 2
        versionName "1.1"
        multiDexEnabled true
        testInstrumentationRunner 'android.support.test.runner.AndroidJUnitRunner'
    }

gradle:
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

**Comment by dxsdyhm** [comment]
* 截图报错希望可以提供日志，或者机型信息
* 错误码都在README的第8点
* 使用P2PView的地方需要继承BaseMoniterActivity，且不要声明

**Comment by haira1987** [comment]
- [log.txt](https://github.com/dxsdyhm/GwellDemo/files/1028002/log.txt)
机型
Coolpad 9190L_C00 
android 4.3,API 18

- 错误码看到了，但没有20000，不知道代表什么意思

**Comment by dxsdyhm** [comment]
* ![](http://7xp6ld.com1.z0.glb.clouddn.com/QQ%E5%9B%BE%E7%89%8720170525140847.png)
这好像是加载图片出错，与SDK无关
* 20000这个错误码库里面没有定义过，你可以截图或者具体提供一下信息，比如日志截图

**Comment by dxsdyhm** [comment]
* ```20000```这个错误后台有定义，是```APPID```与```APPTOKEN```信息错误，但理论上不应该返回```20000```而是新版错误码，这可能是服务器的一个BUG,不过你的这个信息应该是填写有问题，
可将你填写的初始化数据发给客服，验证一下
* ```P2PView```的```0.3.8```版本外面必须套一层Relativelayout

**Comment by haira1987** [comment]
我复制了你们的activity_monitoer.xml和MonitoerActivity文件到我项目中，但运行报下面错误

05-26 12:54:19.339: E/AndroidRuntime(3499): FATAL EXCEPTION: main
05-26 12:54:19.339: E/AndroidRuntime(3499): java.lang.UnsatisfiedLinkError: Couldn't load SDL from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.or_home-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.or_home-2, /vendor/lib, /system/lib]]]: findLibrary returned null
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at java.lang.Runtime.loadLibrary(Runtime.java:355)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at java.lang.System.loadLibrary(System.java:525)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at com.p2p.core.MediaPlayer.<clinit>(MediaPlayer.java:67)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at com.p2p.core.BaseP2PviewActivity.onCreate(BaseP2PviewActivity.java:29)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at com.p2p.core.BaseMonitorActivity.onCreate(BaseMonitorActivity.java:36)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at youdao.haira.smarthome.Gwell.MonitoerActivity.onCreate(MonitoerActivity.java:88)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.app.Activity.performCreate(Activity.java:5146)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2191)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2282)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.app.ActivityThread.access$600(ActivityThread.java:147)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.os.Looper.loop(Looper.java:137)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at android.app.ActivityThread.main(ActivityThread.java:5265)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at java.lang.reflect.Method.invoke(Method.java:525)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
05-26 12:54:19.339: E/AndroidRuntime(3499): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by dxsdyhm** [comment]
这是编译时编译了其他指令集的动态库到APK中，采用打包过滤应该可以解决，在主工程的gradle中增加
```Groovy
android {
    ...
    defaultConfig {
       ...
        ndk {
            abiFilters "armeabi"
        }
    }
```
