### ISSUE TITLE
语音没有效果

### ISSUE THREAD

**Issue by 18359422169** [dxsdyhm/GwellDemo#26]
语音对讲功能

**Comment by 18359422169** [comment]
setMute（false） 声音发不出来,是不是底层so库有问题,用的是com.p2p.core:p2p-core:0.3.1这个版本

**Comment by huangdali** [comment]
你是直接运行demo的apk不能正常语音对讲吗？

**Comment by huangdali** [comment]
我测试了一下最新版的demo是能正常语音对讲的，你也试试下载最新版的demo运行看看是否有这个问题https://fir.im/smya

**Comment by huangdali** [comment]
注意到你使用的是0.3.1版本，这个版本确实有点问题，0.3.8已修复这个问题，你可以升级到0.3.8即可解决

**Comment by foreverGoUp** [comment]
门铃设备通电通网的状态下，demo点击监控进去，再直接点击监控按钮会闪退！自动跳回到首页，最上面出现一行红色字体：“p2p未连接，请重试！”。在线等，急！

**Comment by 18359422169** [comment]
已经确认了，有个语音的权限没加进去，，，，
