### ISSUE TITLE
Demo首页点击监控进去，再点击监控闪退

### ISSUE THREAD

**Issue by foreverGoUp** [dxsdyhm/GwellDemo#27]
门铃设备通电通网的状态下，demo点击监控进去，再直接点击监控按钮会闪退！自动跳回到首页，最上面出现一行红色字体：“p2p未连接，请重试！”。在线等，急！

![screenshot_20170606-103920](https://cloud.githubusercontent.com/assets/20222580/26811771/740d0c70-4aa6-11e7-8e78-1c978e8d4fd3.png)
![img_20170606_103955](https://cloud.githubusercontent.com/assets/20222580/26811778/7960ffec-4aa6-11e7-9b0e-2e3abe9316fb.png)

**Comment by dxsdyhm** [comment]
监控页游ID输入与密码输入框  ，直接点监控之前是不是没有输入这些信息？

**Comment by foreverGoUp** [comment]
居然还有这种操作！希望下次能在输入框内加个提示（笑哭）。 @dxsdyhm

**Comment by dxsdyhm** [comment]
现在已经添加了输入判断
