### ISSUE TITLE
使用HttpSend的登录接口，返回的结果有问题！

### ISSUE THREAD

**Issue by foreverGoUp** [dxsdyhm/GwellDemo#28]
使用正确和错误的手机号和密码登录，返回的对象里字段都是null值。
![aaa](https://cloud.githubusercontent.com/assets/20222580/26812326/a927df36-4aa9-11e7-8738-5218ae26a827.png)

返回数据打印：
onNext LoginResult{UserID='null', P2PVerifyCode1='null', P2PVerifyCode2='null', Email='null', NickName='null', CountryCode='null', PhoneNO='null', ImageID='null', SessionID='null', DomainList='null', UserLevel='null'}

**Comment by dxsdyhm** [comment]
LoginResult  有个getErrorCode的方法 ，请打印并告知这个错误码

**Comment by foreverGoUp** [comment]
/**
     * APP信息(AppID、AppToken、包名等)不正确
     */
    public static final String ERROR_10901050 = "10901050";

谢谢你的回复，今天才看到，我一直以为错误码是在回调的onError方法中，这个你们需要在显眼的地方专门作个说明了。按照你的提示，返回的是这个错误码，我现在去向你们公司的人申请一下新的AppID、AppToken、包名再试试。 @dxsdyhm

**Comment by dxsdyhm** [comment]
好的
这个  新版中已经修改了，erroecode在父类  而子类在复写tostring的时候没有带上父类，下一版本应该就不会隐藏在里面了
