### ISSUE TITLE
开发参考文档链接失效

### ISSUE THREAD

**Issue by foreverGoUp** [dxsdyhm/GwellDemo#34]
readme中的硬件接口说明链接失效，请重新提供~

![image](https://user-images.githubusercontent.com/20222580/26972041-75d651da-4d42-11e7-920a-1bcaa54e03fb.png)

**Comment by dxsdyhm** [comment]
* 抱歉，这个硬件接口说明暂时还没有提供，如果有具体功能上的问题可在这里说明（节假日）或者技术支持（工作日）

**Comment by foreverGoUp** [comment]
请问访客按门铃之后，P2PListener中的哪个方法被回调？？demo中的注释是说这个方法会被回调:vAllarmingWitghTime，然而并没有，该类中的其他方法也没有一个被回调。 @dxsdyhm

**Comment by dxsdyhm** [comment]
访客按门铃的回掉其实和门铃具体的设备种类有关系（我们的设备体系中有两种）
1.通过串口通信
2.通过GPIO口通信
串口通信的话是通过```vRetCustomCmd```这个接口返回
GPIO通信时通过```vAllarmingWitghTime```返回（如果收不到，检查用户ID是否在设备的推送列表中）

**Comment by foreverGoUp** [comment]
那如何区别门铃的设备种类？用哪个api可以检查用户ID是否在设备的推送列表中？请尽快完善demo中的访客呼叫模块，谢谢~ @dxsdyhm

**Comment by dxsdyhm** [comment]
* 你们设备端只会是某一种 不会多种，咨询一下设备相关的人就知道门铃是怎么告知APP有人来访的
* 获取报警绑定ID接口就可以检查自己在不在列表中```getBindAlarmId```
* 访客呼叫设备有什么问题么？和管理员呼叫（监控）设备是一样的
*

**Comment by foreverGoUp** [comment]
调用getBindAlarmId出现下面的crash：
-------------------------------------------------------------

 Caused by: java.lang.NumberFormatException: Invalid int: "jy123456"
                                                               at java.lang.Integer.invalidInt(Integer.java:137)
                                                               at java.lang.Integer.parse(Integer.java:374)
                                                               at java.lang.Integer.parseInt(Integer.java:365)
                                                               at java.lang.Integer.parseInt(Integer.java:331)
                                                               at com.p2p.core.P2PHandler.getBindAlarmId(P2PHandler.java:708)
                                                               at com.jy.activity.device.DoorBellPlayActivity.onClick(DoorBellPlayActivity.java:214)
-------------------------------------------------------------

这个接口支持的设备密码怎么只能是数字？？ @dxsdyhm

**Comment by dxsdyhm** [comment]
只能是数字，如果你要启用字母密码的话  需要全部转换为数字
SDK提供了一个转换方法EntryPassword（参考SDK里面的所有密码输入框）
这个方法保证相同输入产生相同的输出
这个逻辑可以仅在密码发生变化的时候做，

**Comment by foreverGoUp** [comment]
问题1、门铃现在支持的最大报警推送账号个数是5个，有没有办法增加这个数量？ 因为一个家庭中同时期望接收到访客呼叫消息的成员数量会大于5。
问题2、有什么接口可以统一管理一个门铃所有已绑定的AlarmId？比如删除一个门铃所有已绑定的AlarmId(为了重新将一些指定账户绑定到门铃上)。 @dxsdyhm

**Comment by dxsdyhm** [comment]
* 5这个限制在不修改设备端的情况下不能修改
* ```getBindAlarmID```与```setBindAlarmID```这一对操作方法就是管理接口（eg:get结果[1,2,3,4,5],删除所有的话就set[]不填任何值就可以  如果删除3号ID则set[1,2,4,5]即可）

**Comment by foreverGoUp** [comment]
@dxsdyhm  现在的问题是，同一个账户（手机号）ios混合登录返回的userid和android登录返回的userid为什么不一样？如果是一个账号在android设备上绑定了设备，在苹果登录就收不到访客通知了。
-----------------------------------------------------------------------------
android登陆代码：
public static void loginDoorBellServerApi(String email, SubscriberListener subscriberListener) {
        String option = WebConfig.Third_Option.ThirdLogin_Option_3;
        String unionID = HttpRegistrant.getInstance().getAPPID() + email;
        String thirdType = WebConfig.PlatFormType.ThirdLogin_PlatFormType_Anonymous_Email;
        try {
            HttpMethods.getInstance().ThirdLogin(option, unionID, "", "", "", thirdType, subscriberListener);
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
    }

ios登录代码：
-(void)thirdLoginWithPlatformType:(NSString*)platformType//平台,1.微信 2.匿名登录 3 混合登录 ,此参数不可空
                      withUnionID:(NSString*)unionID//第三方平台的唯一标识符,如果是匿名登录,提供设备的唯一标识即可,不可空
                         withUser:(NSString*)user//用户名,可为手机,如+86-15200002222,或邮箱,或ID号,如010000,绑定账号时不可空
                     withPassword:(NSString*)pwd//密码,需要32位的md5加密处理,如果提供明文密码,内部会自动加密,绑定账号时不可空
                   withAppleToken:(NSString*)token//苹果设备Token,用来远程推送,可空,空时则无法推送
                       withOption:(NSString*)option//1仅登录 2绑定老用户并登录 3登录,若不存在则自动注册
                      withStoreID:(NSString*)storeID//商城ID,需要商城版功能时必须上传,可空,不懂的话留空即可
                       completion:(GWNetCompletionBlock)completion;//请求完成回调

**Comment by dxsdyhm** [comment]
1.你打印确认一下 email 和unionID 是否一样

**Comment by foreverGoUp** [comment]
不一样的 @dxsdyhm

**Comment by dxsdyhm** [comment]
不一样当然会返回不一样的userID啊
这个东西相当于用户名

**Comment by foreverGoUp** [comment]
我测试时是同一个账号分别用ios和android的门铃SDK登录的啊！如果返回的userId不一样，那么同一个账号绑定到一个门铃设备就相当于绑定了2次。举个例子，就如13800000000->[2,3]，其中假设2为ios返回的UserId，3为android返回的userId。但是正常情况下同一个账户用ios和android登录你们的服务端返回的应该是相同的UserId啊，这样一个用户只要在android应用上绑定到门铃设备，换到ios应用登录后直接就能收到访客呼叫了（当访客呼叫时），而不需要再次绑定。 @dxsdyhm

**Comment by foreverGoUp** [comment]
还有个问题请教一下。访客呼叫时，用户点击挂断图标并且可以不让呼叫再进来的接口是哪一个？我现在用P2PHandler.getInstance().reject();无效，呼叫还是可以进来，而且我自己写了一个逻辑20s内相同的呼叫我直接忽视。 @dxsdyhm

**Comment by dxsdyhm** [comment]
不让呼叫  你是准备永远不呼叫 还是某一段 时间不呼叫？
如果是永远 你解除绑定就可以了
如果是一段时间  你现在的逻辑就是对的只不过20 这个值按需求定就行了

**Comment by dxsdyhm** [comment]
对于上一个问题 ，我们服务器保证相同的登陆信息不管平台 返回的ID都是相同的
出现这种情况一定是你不同端传的信息不一样，你需要检查一下输入信息

**Comment by foreverGoUp** [comment]
回答呼叫的问题：
现在的情况是，在只按一次门铃呼叫按钮的情况下，我代码拒绝（“P2PHandler.getInstance().reject();”）后，然后20s甚至是40s后同一个呼叫（40s之内未再次按门铃呼叫）还会进来！但是我试过你们官方门铃app，在上面相同的情况下不会再次进来骚扰，是你们设置比较久的忽略时间还是用了一个可以实际拒绝本次呼叫的接口？ @dxsdyhm

**Comment by foreverGoUp** [comment]
我和ios登录时传入以下登录接口的账号参数现在直接是手机号（例如13800000000），然后返回的userId也还是不一样，为什么？是参数格式不正确吗？还是有其他原因？@dxsdyhm

ps：1、我现在直接将email传入android的登录接口：“HttpMethods.getInstance().ThirdLogin(option, email, "", "", "", thirdType,  subscriberListener);”
2、ios那边原本就是直接传入email参数的，没有进行任何处理。
3、也就是说android和ios登录时email==unionID 。
------------------------------------------------------------------------------------------------------
android登陆代码：
public static void loginDoorBellServerApi(String email, SubscriberListener subscriberListener) {
String option = WebConfig.Third_Option.ThirdLogin_Option_3;
String unionID = HttpRegistrant.getInstance().getAPPID() + email;
String thirdType = WebConfig.PlatFormType.ThirdLogin_PlatFormType_Anonymous_Email;
try {
HttpMethods.getInstance().ThirdLogin(option, unionID, "", "", "", thirdType, subscriberListener);
} catch (UnsupportedEncodingException e) {
e.printStackTrace();
} catch (NoSuchAlgorithmException e) {
e.printStackTrace();
}
}

ios登录代码：
-(void)thirdLoginWithPlatformType:(NSString*)platformType//平台,1.微信 2.匿名登录 3 混合登录 ,此参数不可空
withUnionID:(NSString*)unionID//第三方平台的唯一标识符,如果是匿名登录,提供设备的唯一标识即可,不可空
withUser:(NSString*)user//用户名,可为手机,如+86-15200002222,或邮箱,或ID号,如010000,绑定账号时不可空
withPassword:(NSString*)pwd//密码,需要32位的md5加密处理,如果提供明文密码,内部会自动加密,绑定账号时不可空
withAppleToken:(NSString*)token//苹果设备Token,用来远程推送,可空,空时则无法推送
withOption:(NSString*)option//1仅登录 2绑定老用户并登录 3登录,若不存在则自动注册
withStoreID:(NSString*)storeID//商城ID,需要商城版功能时必须上传,可空,不懂的话留空即可
completion:(GWNetCompletionBlock)completion;//请求完成回调

**Comment by foreverGoUp** [comment]
你们有没有测试过用ios和android混合登录接口同一个账号登录返回的userid是否一样呢？我和ios现在都用上了你们公司分配的参数，同一个账号登陆ios和android返回的结果让人大跌眼镜！我的userId格式还是正常的，ios返回的是“00”，“00”这是什么鬼。 @dxsdyhm

**Comment by dxsdyhm** [comment]
我们的微信登陆就是用的混合登陆接口
我们的正式工程是测试过的（微信登陆测试的，不知道是否具有代表性）
至于Demo还没有做个过测试

**Comment by foreverGoUp** [comment]
咱们一个个问题解决：
1、回答呼叫的问题：
现在的情况是，在只按一次门铃呼叫按钮的情况下，我代码拒绝（“P2PHandler.getInstance().reject();”）后，然后20s甚至是40s后同一个呼叫（40s之内未再次按门铃呼叫）还会进来！但是我试过你们官方门铃app，在上面相同的情况下不会再次进来骚扰，是你们设置比较久的忽略时间还是用了一个可以实际拒绝本次呼叫的接口？ @dxsdyhm

**Comment by dxsdyhm** [comment]
1.不知道你用官方门铃APP的时候，拒绝是点的哪个按钮？
2.门铃在同一次呼叫APP的过程中多次按铃，只会推送一次
3.我们APP对于每一个摄像头的推送，拒绝后都是默认10S内不再接受推送，这是通过APP逻辑来实现的（10S内相同ID则忽略）
4.拒绝本次呼叫确实是用```P2PHandler.getInstance().reject();```这个指令
5.你说的40S后同一个呼叫  其实已经是第二次呼叫了，原则上是应该有响应的

**Comment by foreverGoUp** [comment]
回复：
1、用官方门铃APP的时候，拒绝点的是访客呼叫界面的拒绝按钮（旁边是前往按钮）。
5、我是40s内拒绝过了（执行了P2PHandler.getInstance().reject();代码），而且没有第二次按下设备上的呼叫按钮。以上情况下第一次的呼叫还是进来了。是你们设置比较久的忽略时间还是用了一个可以实际拒绝本次呼叫的接口？ @dxsdyhm

**Comment by dxsdyhm** [comment]
1.按你的描述  我理解的是只按一次门铃，APP收到有人来访并挂掉，不再按门铃第二次，40S后又有一次有人来访？
2.我们没有设置比较久的忽略时间，
3.你说的门铃呼叫应该只是一次事件推送，这个推送每次事件只会推送一次，并没有你说的拒绝本次呼叫的需求，你finish掉这条消息就可以了

如果第一点的情况属实，可能是个BUG,但这个可能性较低，所以估计还是有什么地方没有沟通清楚，如果还有疑惑可以打电话给技术支持

**Comment by foreverGoUp** [comment]
回复：
请问技术支持的电话是？
@dxsdyhm

**Comment by dxsdyhm** [comment]
你一直都没有其他渠道联系我们的技术支持？
电话不太适合直接在这里公开，
我以为你是有技术支持的QQ之类的，你可以在QQ上问的

**Comment by foreverGoUp** [comment]
这有的。我以为你给了可以直接和你们的技术进行交流，毕竟通过QQ那个人还要转告你们。 @dxsdyhm

**Comment by dxsdyhm** [comment]
如果他们觉得有必要转接 ，是会转接的
