### ISSUE TITLE
获取设备列表问题

### ISSUE THREAD

**Issue by foreverGoUp** [dxsdyhm/GwellDemo#35]
用HttpSend的getDeviceList方法获取结果如下：
![qq 20170610141151](https://user-images.githubusercontent.com/20222580/27000557-d4ddb25e-4de7-11e7-8daa-b624dd47be29.png)
原因是会话id无效，我发现我登录成功后都没有在任何地方设置过这个会话id。
于是我想找个api去设置我登录成功后收到的会话id值。
问题来了：
github中api文档的p2p的连接api中有会话id参数，如下：
“p2pConnect(java.lang.String activeUser, int sessionid1, int sessionid2, int codeStr1, int codeStr2)”
但是！实际依赖的p2p库中的相应方法没有会话id参数，如下：
boolean scs = P2PHandler.getInstance().p2pConnect(result.getUserID(), code1, code2);

那么请问：
1、请求设备列表是使用HttpSend中的getDeviceList这个api吗？？
2、这个会话id要用哪个api设置到sdk里？？

**Comment by dxsdyhm** [comment]
* 设备列表保存服务器是最新的功能，也仅仅在Yoosee17版中做，涉及很多内容（加密与同步），不建议现在使用
* 对于API与库的方法不对应的问题，是由于API更新速度较快，产生的暂时不对应，（极个别方法）
* 假如要使用WebAPI（HttpSend）,第一步是登录，登录成功之后SDK会将sessionID缓存起来，以后的web请求自动加上这个参数（P2P指令（P2PHandler）不需要此参数(仅需要code1与code2)）

**Comment by dxsdyhm** [comment]
* 请求的设备列表也是由APP上传的，这部分会尽快出说明文档，不过可能需要一点时间
