### ISSUE TITLE
希望不要用@BindView方法，还是用findViewById方法，做model的时候全部报错

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#42]
![qq 20170731101010](https://user-images.githubusercontent.com/19991872/28760312-9c710592-75d8-11e7-8a1b-378223c995c3.png)

**Comment by dxsdyhm** [comment]
Demo 不能作为Modle
只能作为示例代码，SDK引入很简单，不需要单弄一个Modle
Demo里面有很多第三方的库，使用基本没有甄别，也不建议直接使用，但都不是SDK必须的库
