### ISSUE TITLE
Demo声波连接，部分型号设备连接失败

### ISSUE THREAD

**Issue by 18359422169** [dxsdyhm/GwellDemo#45]
Demo声波连接，部分型号设备连接失败，海思的V100就无法进行声波连接，固件版本13.0.0.99

**Comment by dxsdyhm** [comment]
@18359422169 配网任何一种方式都需要设备配合
这种情况需要确认设备是否支持（拿Yoosee测试，Yoosee的智能联机是智能联机+声波同时配网的）
同时，也建议这两种方式一起配网，他们的应答都是一样的（8899端口）
