### ISSUE TITLE
yoosee的ap配网，设备列表怎么来的

### ISSUE THREAD

**Issue by 18359422169** [dxsdyhm/GwellDemo#47]
还没有配网成功有个，设备列表，是如何搜索到还没联网的设备。
 MyUtils.getApSendWifi(apDeciceid, ssidName, ssidPwd, ssidType, devicePwd);就是这个方法的apDeciceid,和devicePwd怎么获取到

**Comment by dxsdyhm** [comment]
@18359422169 apDeviceID是在SSID后面附带的格式一般为Gwell_AP_XXXXXX（ID）
devicePwd是用户输入的密码
