### ISSUE TITLE
关于注册登录以及设备获取

### ISSUE THREAD

**Issue by JJOGGER** [dxsdyhm/GwellDemo#48]
请问注册是不是一定要走带验证码参数的接口？我们自己集成到自己的app中不行么？还有现在是不是没有提供获取设备列表的方法？

**Comment by dxsdyhm** [comment]
@JJOGGER 关于第三方登陆（第三方用自己的账户系统），可以使用第三方登陆接口（免注册）
设备列表接口是一个比较复杂的同步体系，接口有（HttpSend），但暂时缺乏文档，设备列表一直都是保存在手机数据库的（Yoosee17版之前）

**Comment by JJOGGER** [comment]
那第三方登录的话，UnionID，User，UserPwd怎么填呢

**Comment by dxsdyhm** [comment]
@JJOGGER 参考SpecialEmailLogin接口，这个接口只需传入第三方用户一个唯一标识字符串即可
例如：QQ     假如腾讯定义QQ号是他们识别用户的唯一字符串，则可以将QQ号传入，
接口保证相同字符串得到相同用户
