### ISSUE TITLE
经常SDK请求会出现网络连接失败的情况，YOOSEE是怎么处理的

### ISSUE THREAD

**Issue by 18359422169** [dxsdyhm/GwellDemo#50]
已经确认这边wifi路由器网络顺畅，调用sdk时候经常会出现连接失败，网络错误的问题

**Comment by dxsdyhm** [comment]
@18359422169 如果是必然出现的或者频率很高，需要检查一下代码
    1.P2P初始化是否正常（SDK可能并没有在运行）
    2.设备是否在线
如果频率比较低 ，Yoosee是在有必要的时候选择重发（但不要都用，不然会是死循环）
