### ISSUE TITLE
如何获取设备登录状态

### ISSUE THREAD

**Issue by JJOGGER** [dxsdyhm/GwellDemo#54]
在进行设备操作的时候经常要传入设备id和密码，那么如何才能确定这个设备id或者密码没有传错呢，有没有回调？

**Comment by dxsdyhm** [comment]
@JJOGGER id 不能错（由开发者保证，如果这个ID操作时服务器没有找到（发出指令没有回应），会认为网络异常），密码错误会有ACK回调（每条指令都有ACK回调，回调的result具体含义在Readme中有说明），
