### ISSUE TITLE
p2p-core这个库与我引用的Rxjava2冲突了，请问p2p-core有没有没有引用Rxjava1的版本。

### ISSUE THREAD

**Issue by leguang** [dxsdyhm/GwellDemo#56]
p2p-core这个库与我引用的Rxjava2冲突了，请问p2p-core有没有未引用Rxjava1的版本。

**Comment by dxsdyhm** [comment]
@leguang 我们只能尽快修改到RxJava2

**Comment by AndyJennifer** [comment]
@leguang 方便问一下你appid 与token是怎么拿到的嘛？

**Comment by dxsdyhm** [comment]
@leguang 最新版已经升级了
