### ISSUE TITLE
第三方匿名登录，返回错误码10901053：APP客户号(内置主版本号)错误，是什么意思？

### ISSUE THREAD

**Issue by liujia95** [dxsdyhm/GwellDemo#57]
下面是我调用的代码：
`HttpSend.getInstance().ThirdLogin("1", BuildConfig.APPLICATION_ID, "", "", "0", "2", subscriberListener)`

**Comment by dxsdyhm** [comment]
@liujia95 查看issue #11

**Comment by dxsdyhm** [comment]
@liujia95 建议使用[SpecialEmailLogin](http://doc.cloud-links.net/SDK/Android/P2PCore/com/p2p/core/P2PSpecial/HttpSend.html#SpecialEmailLogin-java.lang.String-com.libhttp.subscribers.SubscriberListener-)
email必须保证能够唯一代表一个用户，除非你不需要区别APP的使用者

**Comment by liujia95** [comment]
1、第三方匿名登录不可以使用吗？
2、我用SpecialEmailLogin的时候，传入的email是必须要在我们APP调用[register](http://doc.cloud-links.net/SDK/Android/P2PCore/com/p2p/core/P2PSpecial/HttpSend.html#register-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.lang.String-com.libhttp.subscribers.SubscriberListener-)注册一次吗？
3、我传了一个用你们这个GwellDemo注册过的邮箱调用SpecialEmailLogin，仍然报错误码10901053：APP客户号(内置主版本号)错误，不清楚这错误是不是第2步没有在我们APP注册的原因。

**Comment by dxsdyhm** [comment]
1.可以用，但是SpecialEmailLogin本质上也是第三方登录，只不过不需要关心其它参数而已
2.不需要注册
3.版本号需要符合一定的格式，具体可以参照Read .ME中的备注第一条

**Comment by liujia95** [comment]
问题已解决，是我的APPVersion填写错误，该问题可关闭，谢谢。
