### ISSUE TITLE
第三方登录问题

### ISSUE THREAD

**Issue by JJOGGER** [dxsdyhm/GwellDemo#58]
android再没修改代码的时候，今天出现一个情况，第三方匿名登录时，登录成功，并且P2P_CONNECT连接也监听到为true，但是监控、设置等其他摇头机的操作突然就不能获取到监听了，这是什么问题？

**Comment by dxsdyhm** [comment]
@JJOGGER 会不会是密码错了或者设备离线了？可以查看一下指令的ACK回调结果

**Comment by JJOGGER** [comment]
不是，问题我也不清楚，下午过来就自己好了。。
另外现在遇到另外一个问题，监控录像的时候，调用录像的过程都正常，但是录制下来的mp4视频播放不了

**Comment by dxsdyhm** [comment]
@JJOGGER 如果使用的0.4.3的话，可以将录制的文件邮件发给我

**Comment by JJOGGER** [comment]
我这边使用的是0.3.8

**Comment by dxsdyhm** [comment]
@JJOGGER 可以试试0.4.3
监控录像，部分摄像头可能有问题，是摄像头传输的视频数据格式有差异

**Comment by ArtistWolf-Developer** [comment]
我現在遇到類似的問題
connect 都得到 true
P2PHandler.getInstance().call(...) 得到的回應也是 true
但是仍然沒有監控的畫面

**Comment by dxsdyhm** [comment]
@JJOGGER Demo可以看到画面么？

**Comment by ArtistWolf-Developer** [comment]
@dxsdyhm 
 從 MonitoerActivity 的 BroadcastReceiver 中取得 Intent 的 Action 都是 P2P_REJECT
監控掛斷(reson:10, code1:806363140, code2:0)

**Comment by dxsdyhm** [comment]
如果初始化正常的话，有可能你的额设备并不在线，可以告知一下你的设备号？

**Comment by ArtistWolf-Developer** [comment]
@dxsdyhm 
device id : 7807092
但我從 App Store 上下載的 App 是可以看到影像的

**Comment by dxsdyhm** [comment]
@JJOGGER 7807092这个设备并不在线，如果发布版APP可以看到画面，可能是因为走了局域网监控
发布版APP在探测到设备是局域网设备时，会优先使用IP监控
