### ISSUE TITLE
第二次打开监控必crash。

### ISSUE THREAD

**Issue by liujia95** [dxsdyhm/GwellDemo#60]
1、在GwellDemo中，点主界面监控按钮跳转页面，输入id，pwd，点监控，可以正常播放。
2、然后返回，重复操作步骤1，就崩了。
3、换了两个手机重复测试，均会崩溃。

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/leo/leo:5.1.1/LMY47V/V8.2.1.0.LXHCNDL:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 10270, tid: 10995, name: Thread-43177  >>> com.aglhz.s1 <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: thread Thread[58,tid=10995,Native,Thread*=0xe2355400,peer=0x13195820,"Thread-43177"] using JNIEnv* from thread Thread[32,tid=11305,Runnable,Thread*=0xe2113000,peer=0x1382aee0,"Thread-46312"]'
    r0 00000000  r1 00002af3  r2 00000006  r3 00000000
    r4 d0105db8  r5 00000006  r6 00000002  r7 0000010c
    r8 00000001  r9 f506f550  sl e2355400  fp cf939120
    ip 00002af3  sp d0104b90  lr f74f98cd  pc f751da50  cpsr 60070010

backtrace:
    #00 pc 00038a50  /system/lib/libc.so (tgkill+12)
    #01 pc 000148c9  /system/lib/libc.so (pthread_kill+52)
    #02 pc 000154e7  /system/lib/libc.so (raise+10)
    #03 pc 00011d7d  /system/lib/libc.so (__libc_android_abort+36)
    #04 pc 0000ffac  /system/lib/libc.so (abort+4)
    #05 pc 00217ca9  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+160)
    #06 pc 000a65db  /system/lib/libart.so (_ZN3art10LogMessageD1Ev+1322)
    #07 pc 001e886b  /system/lib/libart.so (_ZN3art7Monitor10VisitLocksEPNS_12StackVisitorEPFvPNS_6mirror6ObjectEPvES6_b+698)
    #08 pc 00225245  /system/lib/libart.so (_ZN3art16StackDumpVisitor10VisitFrameEv+348)
    #09 pc 00220675  /system/lib/libart.so (_ZN3art12StackVisitor9WalkStackEb+684)
    #10 pc 0022608d  /system/lib/libart.so (_ZNK3art6Thread13DumpJavaStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+168)
    #11 pc 002276b1  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+152)
    #12 pc 00230791  /system/lib/libart.so (_ZN3art10ThreadList10DumpLockedERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+104)
    #13 pc 00217a05  /system/lib/libart.so (_ZN3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+236)
    #14 pc 00217c51  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+72)
    #15 pc 000a65db  /system/lib/libart.so (_ZN3art10LogMessageD1Ev+1322)
    #16 pc 000b02e9  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+1076)
    #17 pc 000b0841  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+60)
    #18 pc 000b38eb  /system/lib/libart.so (_ZN3art11ScopedCheckC2EP7_JNIEnviPKc+1134)
    #19 pc 000bb17f  /system/lib/libart.so (_ZN3art8CheckJNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+30)
    #20 pc 0002ab07  /data/app/com.aglhz.s1-2/lib/arm/libSDL.so (_ZN7_JNIEnv20CallStaticVoidMethodEP7_jclassP10_jmethodIDz+18)
    #21 pc 0002ad61  /data/app/com.aglhz.s1-2/lib/arm/libSDL.so (Android_JNI_SwapWindow+68)
    #22 pc 00063d43  /data/app/com.aglhz.s1-2/lib/arm/libSDL.so (Android_GL_SwapWindow+2)
    #23 pc 00063b3b  /data/app/com.aglhz.s1-2/lib/arm/libSDL.so (SDL_GL_SwapWindow+62)
    #24 pc 0000fbf1  /data/app/com.aglhz.s1-2/lib/arm/libSDL.so (SDL_GL_SwapBuffers+8)
    #25 pc 0007dc05  /data/app/com.aglhz.s1-2/lib/arm/libmediaplayer.so (gles2_display+996)
    #26 pc 000835fb  /data/app/com.aglhz.s1-2/lib/arm/libmediaplayer.so (_ZN11MediaPlayer10event_loopEv+750)
    #27 pc 00083795  /data/app/com.aglhz.s1-2/lib/arm/libmediaplayer.so (_ZN11MediaPlayer12StartSendingEi+184)
    #28 pc 00080c27  /data/app/com.aglhz.s1-2/lib/arm/libmediaplayer.so
    #29 pc 000a24e1  /system/lib/libart.so (art_quick_generic_jni_trampoline+32)
    #30 pc 000a9a2c  /dev/ashmem/dalvik-non moving space (deleted)

**Comment by dxsdyhm** [comment]
@liujia95 GwellDemo是在我们提供的链接中下载的么？还是你自己编译的？

**Comment by liujia95** [comment]
@dxsdyhm 自己编译的，不过刚刚从你们提供的链接下载了一个，重复以上步骤仍旧会崩。
但这次崩溃之前屏幕会先绿一下。

**Comment by dxsdyhm** [comment]
@liujia95 这个是Demo方法调用的问题，现在已经解决，参见[commit a161899](https://github.com/dxsdyhm/GwellDemo/commit/a1618994f821e4519ae0ce39a11fe72854015a65)
