### ISSUE TITLE
请问清空SD卡和保存录像的API是哪个，Demo中也没有。

### ISSUE THREAD

**Issue by liujia95** [dxsdyhm/GwellDemo#61]
我用Demo录像，回放列表查找不到刚刚录过的，却在本地找到了，而且startRecoding是要传一个本地地址，所以说Android端的录像不是保存到设备的SD卡中，而是保存到手机本地的吗？

**Comment by liujia95** [comment]
Android端的录像是保存到手机本地的的？不是保存到设备的SD卡中的吗？

**Comment by liujia95** [comment]
你好我还有个问题想请教下，P2PView在视频播放之前会有一段时间为透明的状态，即使给它父容器添加黑色背景，P2PView仍然会透明显示上一个页面，这个有什么方法可以解决吗？

**Comment by dxsdyhm** [comment]
@liujia95 
* 清空SD卡，这个SD卡如果是指设备的SD卡的话，现在不支持删除设备SD的内容（包含清空）  
* startRecoding这个接口是保存在手机SD卡的，保存在设备需要调用P2P指令（P2PHandler）可以选择定时录像，报警录像，手动录像三种模式

**Comment by dxsdyhm** [comment]
@liujia95 后面的这个问题之前写Demo也遇到过，好像是主题的中的```windowContentOverlay```（demo中的监控页是全屏（fullScreeen主题）的）
这个属性有作用，具体如何解决的，现在已经记不清了，你可以试试这个属性
