### ISSUE TITLE
调用P2PHandler.getInstance().call未走P2PListener的回调

### ISSUE THREAD

**Issue by liujia95** [dxsdyhm/GwellDemo#63]
设备：Samsung SM-J7108

1、有时候调用P2PHandler.getInstance().call()方法，P2PListener中没有走回调。
目前摸索出来的导致这个问题的可能性大抵是在视频正常播放的时候，从后台将应用直接杀死，猜测有没有可能是由于没有调用P2PHandler.getInstance().finish()导致的问题，用（从后台将应用直接杀死）这种方式貌似可以稳定重现该bug。因为有时候正常使用也突然会不走P2PListener的回调，以至于广播迟迟未回调，界面一直处于加载模式中。

另一个问题：
2、有时候画面不能正常出来，但语音可以正常播放，退出去重新进来又正常了。

这些问题均不稳定重现在Samsung SM-J7108设备上，其他设备不会出现这些问题。

**Comment by dxsdyhm** [comment]
@liujia95 
1.关于第二个问题可能和设备或者服务器（BUG）有关系,有一段时间我们的APP也遇到相同的情况，按同事的说法，不知道你们现在还是否经常出现
2.关于第一个问题。不知道后台杀死之后有没有重新初始化P2P的过程?如果P2P工作正常，call这个指令是会有超时回调的（reject）,不知道你说的不走P2PListner回调时指哪个回调？
3.如果只在一类手机上出现，这种情况还是比较奇怪的，也有可能是测试误差（环境与网络）。

**Comment by liujia95** [comment]
@dxsdyhm 
1、以上问题（1，2）都是在一个同事手机上会不稳定的重现，现在偶尔依然会出现。
2、有重新初始化P2P的过程，因为在其他手机用后台杀死程序该方式测试都正常，我说的不走P2PListener回调是连reject都不走，我在P2PListener的每个方法中都打印了Log，结果是没有走任何一个方法。也就是调用P2PHandler.getInstance().call()之后，就无回调了。
3、关于测试误差感觉也不太确定吧，因为都是同一时段测试的，网络与环境应该不会有什么误差。
