### ISSUE TITLE
移动侦测获取的图片

### ISSUE THREAD

**Issue by JJOGGER** [dxsdyhm/GwellDemo#64]
请问侦测获取到的图片有时候是完整的，有时候又是不完整的图片，这个是什么问题？

**Comment by dxsdyhm** [comment]
@JJOGGER 首先可已排除是设备还是SDK的问题，出现不完整的图片的时候去设备的SD卡查看同名文件（路径已经传到APP）,如果也是不完整的就和SDK无关

2.报警取图的功能，设备端的流程是异步的，也就是报警发生时先生成路径并马上通知APP,同时开始截图
，通知APP并没有等待截图的结果（设备那边是从报警及时度考虑的（不清楚截图要多久）），
3.以上逻辑看，如果是设备端也是不完整的的话，也可以理解，就不知道能不能改了

4.如果设备是正常的，也有可能是下载图片的时候没有等待图片下载完成就去显示（读取）图片了

**Comment by JJOGGER** [comment]
我这边排查后，觉得应该是第4种原因，我有个方法可以获取到进度GetAllarmImageProgress；但是这个方法达到100之后并没有回调任务完成，所以我这边没不知道什么时候图片下载完成？请问有什么合适的处理方式么

**Comment by JJOGGER** [comment]
我尝试只调用获取图片的接口而不显示图片，但是在手机sd卡里查看到的图片仍然有些图片是有问题的，与其说不完整，不如说是像是好几张图片折叠了一样、会不会是你们接口将图片写入到手机的时候传输的流有问题？

**Comment by dxsdyhm** [comment]
1.你可以将设备的图片和手机的图片都取出来看看么？
2.达到100就是完成了，这里如果非要一个完成的标记的话也只能由上层封装一下....

**Comment by JJOGGER** [comment]
发到你邮箱么

**Comment by JJOGGER** [comment]
1.发到你邮箱么？
2.我用定时器去获取进度，但是达到100之后进度值就变成0了，所以我没办法准确地获取到图片下载完成了

**Comment by dxsdyhm** [comment]
发邮箱可以 duanxuesong12@126.com

**Comment by dxsdyhm** [comment]
1.有没有可能一次推送多次报警，导致图片异常（取图接口不支持多线程（P2P简易传输接口））？
2.如果可以的话，可以将设备号和密码提供，这边用Demo和Yoosee测试一下。
3.Demo中是手动取某一张图所以不会同时在取两张，但是真实代码中取图应该是报警触发的，是有可能同时取多张图的

以上猜测如果解决不了的话，可能需要将这部分代码提供一下。（既然设备图片是正常的，那应该就是SDK或者使用的问题）

**Comment by JJOGGER** [comment]
1.这边是打印出来只报警了一次；
2.8604113，123
3.相关代码通过邮箱发送

**Comment by dxsdyhm** [comment]
1.设备没有SD卡？
2.摄像头对着天花板 没法报警测试

现在下班了，明天再跟进一下吧

**Comment by JJOGGER** [comment]
1.有sd卡；
2.可以加Q么？980328722

**Comment by dxsdyhm** [comment]
1.我们排查一下设备的BUG先，
2.现在怀疑是推送多个APP的原因，你可以测试一下（将非测试报警推送账号删除（仅留一个测试账号））
   再次报警

**Comment by JJOGGER** [comment]
经过多次测试，2部手机同时开推送的时候，偶尔会发生某一台手机接收到的图片不完整或者收不到图片的情况，只有1部手机开推送的时候没有发生图片有问题的情况。
这个问题有解决方案么？

**Comment by dxsdyhm** [comment]
暂时APP没有办法避免，设备端在解决，解决之后会发布固件升级包，设备升级后就正常了
