### ISSUE TITLE
门铃有推送功能吗？Ap配网,按了复位按钮，手机wifi没搜索到热点

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#66]
门铃有推送功能吗？Ap配网,按了复位按钮，手机wifi没搜索到热点

**Comment by dxsdyhm** [comment]
1.门铃有报警推送
2.AP配网对设备有要求，具体可以询问技术支持

**Comment by haira1987** [comment]
Smartlink配网是不是所有设备都可以使用

**Comment by haira1987** [comment]
推送有关掉进程也能推送的吗

**Comment by dxsdyhm** [comment]
1.Android  关掉进程收不到推送
2.smartlink 是都支持的（准确的信息以技术支持为准）

**Comment by haira1987** [comment]
有人按门铃，怎么挂掉，不接听， P2PHandler.getInstance().reject();没用

**Comment by dxsdyhm** [comment]
有两种不同程度的不接听
* 仅手机这边“挂断”：APP只需要销毁UI就行了，因为门铃推送过来的时候是一个消息，不需要挂断，还没有正式呼叫，你现在用的``` P2PHandler.getInstance().reject();```是专门用于呼叫接通后的挂断
* 这个“挂断”还需要让门铃响应（比如“嘟嘟”声停止）：这个是没有消息命令回执的

大部分需求是第一种，具体问题可以再咨询技术支持
