### ISSUE TITLE
RF device ID

### ISSUE THREAD

**Issue by AndreyKlevtsov** [dxsdyhm/GwellDemo#67]
RF sensor has an ID number of 24bits.
We need get this ID from added sensors and method to add sensor by ID.
Does P2Phandler allow it?
Is it in yours plans?

**Comment by dxsdyhm** [comment]
Please ask our technical support

**Comment by AndreyKlevtsov** [comment]
Can you tell the correct contact info of tech support, please?

**Comment by dxsdyhm** [comment]
Our customers have links to the line, if you do not know, you can find your company or colleagues (or tell you the library (link) people), due to limited manpower, forgive us can not provide technical support to individuals.

**Comment by AndreyKlevtsov** [comment]
Thank you
