### ISSUE TITLE
更新到android studio3.0 报了以下错误

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#69]
10-27 10:54:10.543: E/dalvikvm(11640): Could not find class 'com.p2p.core.P2PSpecial.P2PSpecial$1', referenced from method com.p2p.core.P2PSpecial.P2PSpecial.Connect
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to resolve new-instance 1819 (Lcom/p2p/core/P2PSpecial/P2PSpecial$1;) in Lcom/p2p/core/P2PSpecial/P2PSpecial;
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to resolve static method 11616: Lcom/p2p/core/P2PSpecial/P2PSpecial$P2PSpecialHolder;.access$100 ()Lcom/p2p/core/P2PSpecial/P2PSpecial;
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to resolve static method 11629: Lcom/p2p/core/P2PSpecial/PhoneIDUtils;.getInstance ()Lcom/p2p/core/P2PSpecial/PhoneIDUtils;
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to resolve static method 11807: Lcom/p2p/core/utils/SharedPrefreUtils;.getInstance ()Lcom/p2p/core/utils/SharedPrefreUtils;
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to find class referenced in signature (Lcom/p2p/core/P2PInterface/IP2P;)
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to find class referenced in signature (Lcom/p2p/core/P2PInterface/IP2P;)
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to resolve static method 11807: Lcom/p2p/core/utils/SharedPrefreUtils;.getInstance ()Lcom/p2p/core/utils/SharedPrefreUtils;
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to resolve static method 11807: Lcom/p2p/core/utils/SharedPrefreUtils;.getInstance ()Lcom/p2p/core/utils/SharedPrefreUtils;
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to resolve static method 11140: Lcom/libhttp/http/HttpRegistrant;.getInstance ()Lcom/libhttp/http/HttpRegistrant;
10-27 10:54:10.543: W/dalvikvm(11640): VFY: unable to resolve static method 11807: Lcom/p2p/core/utils/SharedPrefreUtils;.getInstance ()Lcom/p2p/core/utils/SharedPrefreUtils;
10-27 10:54:10.543: W/dalvikvm(11640): threadid=1: thread exiting with uncaught exception (group=0x41889940)
10-27 10:54:10.543: E/AndroidRuntime(11640): FATAL EXCEPTION: main
10-27 10:54:10.543: E/AndroidRuntime(11640): java.lang.NoClassDefFoundError: com.p2p.core.P2PSpecial.P2PSpecial$P2PSpecialHolder
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at com.p2p.core.P2PSpecial.P2PSpecial.getInstance(P2PSpecial.java:43)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at youdao.haira.smarthome.EZ.EzvizApplication.initP2P(EzvizApplication.java:55)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at youdao.haira.smarthome.EZ.EzvizApplication.onCreate(EzvizApplication.java:49)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4570)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at android.app.ActivityThread.access$1300(ActivityThread.java:147)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at android.os.Looper.loop(Looper.java:137)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at android.app.ActivityThread.main(ActivityThread.java:5265)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at java.lang.reflect.Method.invoke(Method.java:525)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
10-27 10:54:10.543: E/AndroidRuntime(11640): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by dxsdyhm** [comment]
这个应该和SDK没有关系的吧，我昨天用Demo在AS 3.0上编译过好像没有问题啊......
这是编译异常还是运行报错？

**Comment by haira1987** [comment]
编译没问题，运行报错

**Comment by dxsdyhm** [comment]
仅仅是升级开发工具就报错了？之前是正常的？

**Comment by haira1987** [comment]
之前正常，就升级了工具出了问题，没改其他地方
