### ISSUE TITLE
smartLink 报错

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#70]
10-30 16:45:46.393: E/libEGL(1600): call to OpenGL ES API with no current context (logged once per thread)
10-30 16:45:46.393: E/libEGL(1600): call to OpenGL ES API with no current context (logged once per thread)
10-30 16:45:46.393: E/libEGL(1600): call to OpenGL ES API with no current context (logged once per thread)
10-30 16:45:46.403: E/libEGL(1600): call to OpenGL ES API with no current context (logged once per thread)
10-30 16:45:46.623: W/dalvikvm(2165): VFY: unable to resolve interface method 20988: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
10-30 16:45:46.633: W/dalvikvm(2165): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
10-30 16:45:46.633: W/dalvikvm(2165): VFY: unable to resolve interface method 20990: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
10-30 16:45:46.633: W/dalvikvm(2165): VFY: unable to resolve interface method 20994: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
10-30 16:45:46.633: W/dalvikvm(2165): VFY: unable to resolve virtual method 795: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
10-30 16:45:46.633: W/dalvikvm(2165): VFY: unable to resolve virtual method 817: Landroid/content/res/TypedArray;.getType (I)I
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 515: Landroid/content/Context;.createDeviceProtectedStorageContext ()Landroid/content/Context;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 524: Landroid/content/Context;.getCodeCacheDir ()Ljava/io/File;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 525: Landroid/content/Context;.getColor (I)I
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 526: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 528: Landroid/content/Context;.getDataDir ()Ljava/io/File;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 529: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 531: Landroid/content/Context;.getExternalCacheDirs ()[Ljava/io/File;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 533: Landroid/content/Context;.getExternalFilesDirs (Ljava/lang/String;)[Ljava/io/File;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 536: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 538: Landroid/content/Context;.getObbDirs ()[Ljava/io/File;
10-30 16:45:46.643: W/dalvikvm(2165): VFY: unable to resolve virtual method 549: Landroid/content/Context;.isDeviceProtectedStorage ()Z

**Comment by dxsdyhm** [comment]
1.Demo是经过验证的
2.这个日志看不出原因，但应该和smartlink没有关系，需要自行排查问题
3.如果仍然怀疑，希望可以看到这部分相关的代码

**Comment by xuxiong3316** [comment]
smartLink 连接新的摄像头，双天线的摇头机，一直连接不上，旧版的没有问题，新版的一直嘟嘟嘟

**Comment by dxsdyhm** [comment]
旧版和新版是什么意思？设备的旧版和新版？smartlink最近应该没有更新吧？

**Comment by xuxiong3316** [comment]
旧版新版，只的是摄像头 ，旧的是早期一个天线的中摇头摄像头，新版是现在的2天线的可以摇头的摄像头。用这个配网，单个天线早期的可以用，新的双天线的这个好像配不了网络，一直嘟嘟嘟，直到超时。使用声音配网好像没有这个问题

**Comment by dxsdyhm** [comment]
这个你要找技术支持哦，这里只解决APP的SDK使用问题
这种情况基本不会是SDK的问题
