### ISSUE TITLE
Fragment

### ISSUE THREAD

**Issue by xuxiong3316** [dxsdyhm/GwellDemo#71]
使用摄像头一定要继承 BaseMonitorActivity 能不能把他改成Fragment ，不然我自己需要继承自己的activity 不能用啊，activity 改成 fragment 应该很好改，可以提供Fragment 吗？急急急啊！！！

**Comment by dxsdyhm** [comment]
1.暂时没有计划改这个地方
2.建议这个页面特殊化（不继承自己的Activity）

**Comment by xuxiong3316** [comment]
转改成Fragment 不是很快啊，能不能 Fragment ，这样可以解决继承自己的Activity啊
