### ISSUE TITLE
获取回放列表一直失败

### ISSUE THREAD

**Issue by pengchen520** [dxsdyhm/GwellDemo#72]
你好，获取回放列表一直失败是怎么回事啊 
      P2PHandler.getInstance().getRecordFiles(deviceId, devicePwd, startDate, endDate);

**Comment by dxsdyhm** [comment]
你用Demo获取正常么？
1.如果正常，请查看P2P初始化是否正常
2.如果不正常，可能是设备离线？或者没有SD卡？

具体可以发送ID与密码（可以直接回复，也可以通过邮件duanxuesong12@126.com回复）
