### ISSUE TITLE
手机找回密码，发送验证码接口有了吗

### ISSUE THREAD

**Issue by clanaid** [dxsdyhm/GwellDemo#74]
现在库里只有一个注册时发送的验证码接口，要找回密码时的接口什么时候会有

**Comment by dxsdyhm** [comment]
@clanaid 发送验证码是一个独立的接口，并不会和某些业务绑定，也就是说注册的那个验证码接口同样可以用于找回密码
```getPhoneCode```

**Comment by clanaid** [comment]
但是调用这个接口时会返回10902020 账号已经被使用的错误

**Comment by dxsdyhm** [comment]
@clanaid 抱歉，后台反馈的结果不是这样的，用这个接口就可以了，我们会更新文档的```HttpSend.getInstance().getAccountByPhoneNO```

**Comment by clanaid** [comment]
好的

**Comment by clanaid** [comment]
调用重置密码报数据库操作错误是什么情况

**Comment by dxsdyhm** [comment]
你可以联系技术客服，发邮件出来后一般要及时一点，在这里不好排查这类错误
邮件的时候最好带上一些你认为重要的信息，或者后续会有人找你了解具体情况
技术客服的联系方式可以通过告诉你这个SDK地址的人索取
