### ISSUE TITLE
智能联机ElianNative.InitSmartConnection错误

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#75]
12-28 14:13:36.073: E/AndroidRuntime(32067): FATAL EXCEPTION: main
12-28 14:13:36.073: E/AndroidRuntime(32067): Process: com.or_home, PID: 32067
12-28 14:13:36.073: E/AndroidRuntime(32067): java.lang.UnsatisfiedLinkError: No implementation found for int youdao.haira.smarthome.gwellui.elian.ElianNative.InitSmartConnection(java.lang.String, int, int) (tried Java_youdao_haira_smarthome_gwellui_elian_ElianNative_InitSmartConnection and Java_youdao_haira_smarthome_gwellui_elian_ElianNative_InitSmartConnection__Ljava_lang_String_2II)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at youdao.haira.smarthome.gwellui.elian.ElianNative.InitSmartConnection(Native Method)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at youdao.haira.smarthome.gwellui.SmartLink.sendWifi(SmartLink.java:127)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at youdao.haira.smarthome.gwellui.SmartLink.onClick(SmartLink.java:103)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at android.view.View.performClick(View.java:5340)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at android.view.View$PerformClick.run(View.java:21695)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at android.os.Handler.handleCallback(Handler.java:819)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at android.os.Handler.dispatchMessage(Handler.java:104)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at android.os.Looper.loop(Looper.java:210)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at android.app.ActivityThread.main(ActivityThread.java:5943)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at java.lang.reflect.Method.invoke(Native Method)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
12-28 14:13:36.073: E/AndroidRuntime(32067): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)

**Comment by clanaid** [comment]
声波配网和智能连接能不能同时进行的

**Comment by dxsdyhm** [comment]
1.从错误来看估计是java文件放错位置了，ElianNative的包名是不可以修改的
```youdao.haira.smarthome.gwellui.elian.ElianNative.InitSmartConnection```这里看，包名已经改了

**Comment by dxsdyhm** [comment]
客户端是可以同时进行的，Yoosee是交替进行的（20秒声波暂停10秒20秒智能联机暂停10秒）总的倒计时110秒

**Comment by clanaid** [comment]
是你们的声波库里面含有智能联机了吗

**Comment by dxsdyhm** [comment]
没有包含，两个库的示例都有，应用层控制就可以了

**Comment by haira1987** [comment]
开始发包后没有其他反应了，我现在想更改指定的设备网络，但这个智能联机好像不用指定登录账户和设备ID

**Comment by clanaid** [comment]
智能连接那里是不是不用管wifi加密方式的

**Comment by dxsdyhm** [comment]
@haira1987 @clanaid 1.智能联机本质工作是将Wi-Fi的SSID与密码广播出去，不需要账户验证与设备ID，协议是私有的，能收到的设备说明是符合要求的
2.是需要区别Wi-Fi的加密方式的
