### ISSUE TITLE
GetAllarmImageProgress方法获取问题

### ISSUE THREAD

**Issue by JJOGGER** [dxsdyhm/GwellDemo#76]
您好，我报警时调用GetAllarmImage请求图片之后，通过GetAllarmImageProgress获取下载进度，每500ms获取一次，但是获取到的经常会是0，而且文件是有下载的，请问这是什么问题？

**Comment by dxsdyhm** [comment]
可能是500ms太长，你可以试着加快频率，比如100ms
如果还没有进度值，再反馈即可（由于这个底层实现的问题，不一定能获取到100这个值（取样精度），Yoosee的做法是超过85即视为下载完成）
