### ISSUE TITLE
有指定设备重设网络功能吗？

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#77]

**Comment by dxsdyhm** [comment]
@haira1987 重设网络具体含义可以理解为，设备已经在使用了A网络（有线或Wi-Fi），现在想换B网络（有线或Wi-Fi）
1.有线换有线，替换网线插口即可
2.Wi-Fi换有线，直接将网线插入设备网口即可，设备会切换到有线（不管有线是否有外网），优先使用有线
3.有线换Wi-Fi或者Wi-Fi换Wi-Fi,手机APP可以设置设备网络，参数为SSID与密码
   相关API:```setNetType```,```setWifi```
看是否是你询问的理解

**Comment by haira1987** [comment]
setWifi方法有个问题,前面两个参数contactId，password，是设备ID和密码吗？，但这个密码我看了源码，它会取整MediaPlayer.iSetNPCWifi(Integer.parseInt(contactId),
				Integer.parseInt(password), MSG_ID_SETTING_WIFI, type,
				name.getBytes(), name.length(), wifiPassword.getBytes(),
				wifiPassword.length());
用了Integer.parseInt(password)，但我密码有英文的导致了发生错误

**Comment by dxsdyhm** [comment]
1.密码都需要用```EntryPassword(java.lang.String password)```这个方法转换一下
2.这是数字密码升级到字母密码的时候加上的
3.后续可能会在SDK内部处理这个步骤，调用者就无需关心这个细节了

**Comment by haira1987** [comment]
现在setWifi方法不报错了，但没有返回值，我怎么知道是否设置成功

**Comment by dxsdyhm** [comment]
@haira1987 1.这个指令比较特殊，设备连接wifi的过程总会有一段时间是断网的，所以没有办法将切换结果返回给APP
2.可通过ACK返回，判断这个指令是否送达设备
3.可以多次刷新页面获取结果
4.设备如果无法连接设置的wifi会重连上一次的网络

**Comment by haira1987** [comment]
setWifi我现在怎么设置都不行，能详解一下参数吗？
1.contactId是登录账号，还是设备ID，或IP地址？
2.password是登录密码，还是设备密码？
3.wifiPassword是需要用EntryPassword加密吗
4.还有需要在同一网段内才能设置setWifi吗？

**Comment by dxsdyhm** [comment]
@haira1987 
1.contactid是设备ID,可以是IP地址末段（仅限局域网）；规律：P2P是APP与设备交互的通道，在connect时已经将userID注册过了（P2P验证），后续的指令发出都是针对设备的（P2P内部已经将userID携带在每条指令之中），所以接口中的目标ID都是设备ID,极少部分接口需要UserID，也不会在第一位
2.有了第一条解释，passworld就是设备密码了；从逻辑上也可以理解，对设备操作，你必须告诉服务器你想操作哪台设备，并且带上密码验证
3.不需要，这一点后续会补充进文档
4.不需要同一网段，setwifi是一条普通P2P指令,他的网络要求与其他指令相同；说明：P2P指令都支持外网与局域网操作（不建议处理局域网的情况），没有外网的局域网只能使用IP(末段),否则两者（IP和ID）皆可

**Comment by haira1987** [comment]
ACK_vRetSetWifi 返回了result是9997，是什么意思，result为多少是成功，有列表吗，分别代表什么意思

**Comment by dxsdyhm** [comment]
@haira1987
1.Demo主页第三点说明“使用”中，解释SettingListner中有说明
2.```P2PConstants.ACK_RET_TYPE```或者参考完整文档[ACK_TYPE](http://doc.cloud-links.net/SDK/Android/P2PCore/) 
3.对于这种常量，可在完整文档中的常量字段页面（包含所有常量集合）搜索
