### ISSUE TITLE
demo在Android studio 3编译不了

### ISSUE THREAD

**Issue by huangsanm** [dxsdyhm/GwellDemo#79]
提示：Operation timed out (Connection timed out)
'http://maven.bughd.com/public/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.pom'

**Comment by dxsdyhm** [comment]
@huangsanm 这是自动上传APK用的，与功能无关，如果暂时还不能解决的话，可以屏蔽掉先，我们这边再看看
在我的AS 3.0上是可以运行的
可能的原因：1.gradle版本不匹配
                      2.插件已经失效或者版本删除
                      3.其他环境相关匹配问题
                      4.......
  ----------------------------------------------------------------------------------------------------------------
因为我的本地环境有这个插件缓存，所以编译正常，现在修改了这部分逻辑，现在已经恢复正常

**Comment by dxsdyhm** [comment]
@huangsanm Demo集成了较多的辅助开发库，对于二次开发并不是必须的，二次开发时只需要p2p-core这个库即可

**Comment by huangsanm** [comment]
@dxsdyhm 方便加个微信吗，我们之前集成了技威的监控，现在需要升级sdk
结果很多都跑不通

**Comment by dxsdyhm** [comment]
@huangsanm 这部分我们有专人负责，你可以直接找我们的技术支持，如果不知道联系方式，可以找告诉你这个Demo地址的人询问

**Comment by huangsanm** [comment]
@dxsdyhm 真正集成只要“compile 'com.p2p.core:p2p-core:0.4.3'”这个就可以了吗？
我们之前集成还添加了
`//声波配网库
    compile 'com.github.jwkj:SoundWaveSender:v2.0.2'

//声波配网库说依赖的udp通讯库，不可删除
    compile 'com.jwkj:udpsender:v2.0.1'`

由于是新接手过来的，所以之前的集成方式不是很清楚

**Comment by dxsdyhm** [comment]
@huangsanm 1.p2p-core是主要负责与设备通信的
                        2.配网库主要是负责将设备联网的（包含声波配网，智能联机等）
之前表述有误，因为Demo仅演示对已经联网的设备操作，所以没有包含配网库，真实工程是需要包含的
这个说明在Demo的功能说明中有：
```
可开发除配网外所有Yoosee已开发的功能，配网在下面说明中单独列出，对于Demo中的内容，会根据实际情况增加;
以下功能已经完成
```

**Comment by huangsanm** [comment]
@dxsdyhm 方便QQ联系吗【442072584】
我看demo里面有一个依赖库是：
compile 'com.github.huangdali:UDPSender:v1.3.9'
我们之前同事添加的依赖库是：
`//声波配网库
    compile 'com.github.jwkj:SoundWaveSender:v2.0.2'
    //声波配网库说依赖的udp通讯库，不可删除
    compile 'com.jwkj:udpsender:v2.0.1'`
请问这两个有什么不一样吗

**Comment by huangdali** [comment]
@huangsanm 你好！
```java
compile 'com.github.huangdali:UDPSender:v1.3.9'
```
这个之前是放在jitpack仓库上的，2.x版本之后都放在JCenter仓库（只是仓库位置变了，库的内容是升级的方式），2.x版本修复了一些bug，建议使用2.x版本（具体用法见UDPSender的地址https://github.com/huangdali/UDPSender ）。
目前最新版
```java
compile 'com.jwkj:udpsender:v2.0.2'
```

**Comment by huangsanm** [comment]
@huangdali 你给的这个地址“https://github.com/huangdali/UDPSender）。”打开是404

**Comment by huangdali** [comment]
@huangsanm 
udpsender库是声波配网库所依赖的库，必须要加上这个库声波配网库才能正常运行，如果你们项目中没有直接用到UDPSender可不用管怎么使用；如果有用到建议看一下UDPSender使用方法

**Comment by huangdali** [comment]
@huangsanm 
udpsender库是声波配网库所依赖的库，必须要加上这个库声波配网库才能正常运行，如果你们项目中没有直接用到UDPSender可不用管怎么使用；如果有用到建议看一下UDPSender使用方法

**Comment by huangdali** [comment]
@huangsanm 再进一下看看

**Comment by huangsanm** [comment]
@huangdali 有用到，有两个依赖库：
`//声波配网库
    compile 'com.github.jwkj:SoundWaveSender:v2.0.2'
    //声波配网库说依赖的udp通讯库，不可删除
    compile 'com.jwkj:udpsender:v2.0.2'`
这两个最新版本在哪里能看到？

**Comment by huangdali** [comment]
@huangsanm 
https://github.com/huangdali/UDPSender

https://github.com/jwkj/SoundwaveDemo

**Comment by huangsanm** [comment]
@huangdali  你好，我是润群的工程师
刚才加了您那边技术支持的QQ，麻烦同意一下
