### ISSUE TITLE
用法

### ISSUE THREAD

**Issue by Ashish1611** [dxsdyhm/GwellDemo#8]
我只是想知道我可以使用p2p-core库来开发应用程序是它的开源

**Comment by dxsdyhm** [comment]
I can not understand what you mean
我不能理解你的意思

**Comment by Ashish1611** [comment]
i want to use p2p-core library available on maven but i dont know  is it publicly available for use means is it open source library for use to develop the new android applications or not

**Comment by dxsdyhm** [comment]
p2p-core library can be used develop the new android applications, but we are not open source for the time being,We will open source(Java Code) in the future,BTW,This is a business project,This library is available to our customers.Are you sure?
if not ,How do you find this Library.....
