### ISSUE TITLE
官方播放界面的当前观看人数

### ISSUE THREAD

**Issue by foreverGoUp** [dxsdyhm/GwellDemo#83]
请问如标题的功能所对应的接口是哪个？我在p2pHandler和HttpSend接口文档中均未找到

**Comment by dxsdyhm** [comment]
@foreverGoUp 
1.在IP2P接口的实现类P2PListner中```vRetPlayNumber```
2.这是个被动接收的回调，设备观看人数变化时回调一次，
3.这类监控数据回调与普通P2P指令回调又区别，所以在IP2P接口中，区别于ISettting接口（主要时普通设置回调）
