### ISSUE TITLE
Android设置新密码问题

### ISSUE THREAD

**Issue by afjzwed** [dxsdyhm/GwellDemo#85]
设置密码方法setDevicePassword(String contactId, String oldPassword,
			String newPassword, String RTSPPwd, String userPwd)中的参数newPassword在注释中可以为字母加数字的组合，可是看源码时发现是用Integer.parseInt(newPassword)方法转整型，不然报错，所以只能用数字密码；但是iOS同事更新到最新版本后修改密码必须要字母和数字组合的新密码，于是iOS端更改后的密码不能被Android端使用，请问这个怎么解决

**Comment by dxsdyhm** [comment]
@afjzwed EntryPwd() 这个可以将字母密码转为数字密码
