### ISSUE TITLE
p2p-core从0.3.8升级到0.4.3,读取so 异常

### ISSUE THREAD

**Issue by foreverGoUp** [dxsdyhm/GwellDemo#86]
原本我已经顺利集成0.3.8的sdk，今天因为一些门铃播放的JNI问题升级到0.4.3.升级之后，再次运行我的app，结果报下面的错误。我以为是我so文件不是最新，所以在该库首页点击了Mediaplayer.so重新下载了并放到我的项目运行，结果异常还是一样。
声明：因为我的项目的特殊性，需要接入一个只支持armeabi-v7a架构的第三方sdk，所以我项目声明支持的ndk只有armeabi-v7a。

麻烦大神帮忙解决一下~

我集成该库的方法：
在build中依赖p2p-core，然后在jniLibs->armeabi-v7a目录下存放3个该库的so文件，如图。
![libs](https://user-images.githubusercontent.com/20222580/35431208-8958c984-02b6-11e8-93d3-145fedcc2afb.png)
调试设备：
![qq 20180126164011](https://user-images.githubusercontent.com/20222580/35431493-a4b2c3f0-02b7-11e8-9f38-fdadf51d36ee.png)

以下是集成0.4.3启动我的app报错的日志截图：
![qq 20180126163732](https://user-images.githubusercontent.com/20222580/35431433-68d239ba-02b7-11e8-95ec-6a44afaf0904.png)
![qq 20180126163823](https://user-images.githubusercontent.com/20222580/35431437-6d90a5d6-02b7-11e8-94a7-50f9f4e31425.png)

**Comment by dxsdyhm** [comment]
@foreverGoUp 如果只支持v7a    那么必然需要其中一个SDK 作出牺牲
1.将第三方的SDK里面的so 移入 armabi文件夹中，并删除v7a的so
2.获取p2p-core里面的so全部放到v7a文件夹中 并在build.gradle中配置 ndk.filter仅支持v7a

ps:获取SO的方法，编译后的APK解压 ，找到lib中的armabi复制即可，不要下载此工程的链接中的文件

**Comment by StoneXL** [comment]
怎么是p2p支持v7a的so  上面那个步骤还能具体点么  qq282346341
