### ISSUE TITLE
摄像头连接成功后，验证密码没有任何回应，之前都没问题，今天发现这个问题

### ISSUE THREAD

**Issue by clanaid** [dxsdyhm/GwellDemo#87]

**Comment by clanaid** [comment]
连接摄像头成功后，是不是根据passwordFlag来判断是否初始化密码还是验证密码

**Comment by dxsdyhm** [comment]
连接摄像头是什么意思？配网成功？还是添加成功？
passwordFlag是哪里传出来的？

**Comment by clanaid** [comment]
摄像头配网成功后，接收设备发回来的udp包中不是有pwdFlag吗

**Comment by dxsdyhm** [comment]
那个是设备是否存在密码的标记
差不多是你说的意思
如果不存在密码，则引导用户设置初始密码
如果存在密码则引导用户输入密码并验证密码是否正确之后再添加到设备列表

**Comment by clanaid** [comment]
对，就是这个，我用P2PHandler.getInstance().checkPassword的方法验证密码，之前settinglistener会有回调ACK_vRetCheckDevicePassword，但现在什么都没有回调了

**Comment by dxsdyhm** [comment]
@clanaid 有没有试一下其他接口，比如设置类的
1.有可能是connect 没有成功（P2P没有连上，但没连上也至少应该有超时的）？

**Comment by clanaid** [comment]
好的我试下其他接口，对啊，记得如果没连接成功之前是会有回调网络错误9998的

**Comment by clanaid** [comment]
最新版本rx2的依赖不了，0.4.3的正常

**Comment by dxsdyhm** [comment]
@clanaid 最新版就是 0.4.3  不要用错了，以Demo的示例中的版本为准，那个标记0.4.2_2是测试遗留的，后面要修改这部分，特殊功能的测试版不会发布上来

**Comment by clanaid** [comment]
但是0.4.3里的还是RXJava1的？还遇到有个0.4.3_20的版本

**Comment by dxsdyhm** [comment]
@clanaid 准备更新一个版本

**Comment by clanaid** [comment]
新版本预计什么时候会更新呢？

**Comment by dxsdyhm** [comment]
@clanaid 现在更新了  0.4.4

**Comment by clanaid** [comment]
好的
