### ISSUE TITLE
华为手机无法读取so文件

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#91]
手机型号：HuAWEI MLA-AL10 安卓版本 6.0。因无法读取so文件报错，
如果用
ndk {
            abiFilters "armeabi"
        }
会影响其他组件。
用demo做module的时候又报了Error:Library projects cannot enable Jack. Jack is enabled in default config.

**Comment by dxsdyhm** [comment]
@haira1987 1.Demo不能作为module使用
2.abi的问题参考 #86
