### ISSUE TITLE
通过SmartLinke连接后，调用监控，输入相应设备id与密码后，返回监控挂断(reson:0,code1:0,code2:0)

### ISSUE THREAD

**Issue by AndyJennifer** [dxsdyhm/GwellDemo#92]
@dxsdyhm @huangdali @lianshangyangguang @jwkj 
P2PHandler.getInstance().call(userId, pwd, true, 1, callID, "","", 2, callID);
    想问一下，ipFlag这个参数，是否是摄像机连接wifi后的网络地址，如果是，我传入后，还是返回监控挂断，pwd那个参数我是随便取的密码

**Comment by huangdali** [comment]
@AndyJennifer 密码要正确才能正常监控哦，不能随便取的

**Comment by AndyJennifer** [comment]
@huangdali 那设置设备的密码设置是在哪个界面呢，我没有看到密码设备的密码设置界面

**Comment by AndyJennifer** [comment]
@huangdali 我通过你们原生的apk给设备设置了密码后，调用demo，输入相应的密码，监控成功。我想问一下给设备设置密码的接口是哪个呢？

**Comment by huangdali** [comment]
@AndyJennifer 使用设备前要给设备配网（让设备连上网），配网不属于SDK的功能。

**Comment by huangdali** [comment]
@AndyJennifer 配网相关说明在github首页：https://github.com/dxsdyhm/GwellDemo 的第7项、配网

**Comment by AndyJennifer** [comment]
@huangdali  知道了。谢谢
