### ISSUE TITLE
支持多终端同时观看的吗？

### ISSUE THREAD

**Issue by clanaid** [dxsdyhm/GwellDemo#94]

**Comment by dxsdyhm** [comment]
@clanaid 支持

**Comment by clanaid** [comment]
但我使用过程中发现，同安卓平台的不能同时观看，有一台会被踢下线，而一台安卓一台苹果同时观看又可以

**Comment by dxsdyhm** [comment]
@clanaid 不会的，前提是APP账号是不同的，不同的APP用户是可以同时观看的（不区分平台）
这个现象是必现的么？如果是，则将测试数据与过程发出来，具体问题我们还需要询问设备端同事；

**Comment by clanaid** [comment]
必须似乎不同的账号吗，有看头APP可以同账号同时观看

**Comment by dxsdyhm** [comment]
1.系统没有主动设计同账号同时观看
2.如果可以同时观看，那段期间可能是两个原因：
    1）踢飞功能失效或者在心跳间隔内，还没来得及踢飞（可以预见的时间内，最后一定会有一个账号异常）
    2）至少有一个账号终端是使用的局域网观看
3.不要给所有用户相同的账号

**Comment by clanaid** [comment]
@dxsdyhm 你们支持国外手机号码注册的吗

**Comment by dxsdyhm** [comment]
@clanaid 部分支持，具体支持国家或地区列表可以问技术支持
