### ISSUE TITLE
获取验证码报错10901050，提示APPID，Token不正确，请问APPID，Token该如何申请？

### ISSUE THREAD

**Issue by AndyJennifer** [dxsdyhm/GwellDemo#96]
@dxsdyhm @huangdali 调用 HttpSend.getInstance().ThirdLogin()，提示包名 appid token不正确。我查看了issure 9 也没有看到技术员的联系方式

**Comment by AndyJennifer** [comment]
@dxsdyhm

**Comment by huangdali** [comment]
您好，您需要联系拿货的厂家，然后找我们业务

**Comment by huangdali** [comment]
联系拿货的厂家，走二次开发的流程，流程走完后会给相关参数
