### ISSUE TITLE
添加设备后，设置相应密码。监控返回密码错误

### ISSUE THREAD

**Issue by AndyJennifer** [dxsdyhm/GwellDemo#97]
1.    DeviceSync deviceSync = new DeviceSync(mDeviceId, P2PHandler.getInstance().EntryPassword(DEFAULT_DEVICE_PWD), TimeUtils.getUTCTime(), deviceName);
第一步中，第一个参数对应摄像头id,第二个参数是加密后的密码，第三个参数是时间，第四个设备名称。
 2.HttpSend.getInstance().addDevice(deviceSync, listener);
通过第二步添加设备成功
3. HttpSend.getInstance().readDevice(preDeviceID, requestCount, myUpgradeFlag, listener);
通过第三步拉去添加的设备信息，
4.P2PHandler.getInstance().call(userId, devicePwd, true, 1, deviceId, deviceIp, "", P2PValue.VideoMode.VIDEO_MODE_SD, deviceId);
通过第三步获取的设备密码进行监控，监控提示密码错误？
@huangdali

**Comment by huangdali** [comment]
监控时，需要将用户输入/设置的明文密码加密，P2PHandler.getInstance().EntryPassword(pwd)再调用call方法

**Comment by huangdali** [comment]
另外，addDevice的时候，需要将密码加密，P2PHandler.getInstance().HTTPEncrypt(NpcCommon.mThreeNum, userPassword, 128)


loadDevice读取设备的时候，需要将密码解密：pwd=P2PHandler.getInstance().HTTPDecrypt(NpcCommon.mThreeNum, device.getSecretKey(), 128);

监控时将此密码再加密P2PHandler.getInstance().EntryPassword(pwd)

**Comment by AndyJennifer** [comment]
@huangdali 
我添加设备的时候设备的密码直接是pwd = P2PHandler.getInstance().EntryPassword(pwd)
当我去拉去设备信息的时候 获取的 DeviceSync.getSecretKey 也就是密码
直接调用call方法。所以应该没有影响。 对了我登录时调用的是SpecialEmailLogin 我不知道有不有影响

**Comment by AndyJennifer** [comment]
@huangdali  

我添加设备的时候密码是 123321..
P2PHandler.getInstance().HTTPEncrypt(NpcCommon.mThreeNum, userPassword, 128)
加密过后zDjI4ThWoLgZpVG/SK0JQw==（添加设备的时候加密后的密码）

拉去设备列表后点击相应设备获取的密码也是zDjI4ThWoLgZpVG/SK0JQw==

然后我解密
pwd=P2PHandler.getInstance().HTTPDecrypt(NpcCommon.mThreeNum, device.getSecretKey(), 128);
pwd=123321..

调用监控
  String finallyPwd = P2PHandler.getInstance().EntryPassword(pwd);//finallyPwd =724605726

监控call方法传入的密码是 finallyPwd  （也就是724605726) 

提示我还是密码错误

**Comment by huangdali** [comment]
@AndyJennifer 你用yoosee添加“已联网设备”看看是否密码正确？（悄悄问一句设备配过网吗？）

**Comment by AndyJennifer** [comment]
@huangdali 通过smartLinke配网的。通过yoose添加已联网设备提示密码错误

**Comment by huangdali** [comment]
@AndyJennifer 那就是密码是真的错了

**Comment by huangdali** [comment]
确保密码正确再监控

**Comment by AndyJennifer** [comment]
意思是我添加设备的时候密码错误了，但是流程走的对的。

**Comment by huangdali** [comment]
估计是你配网哪个步骤有问题；建议您到 http://www.wandoujia.com/apps/com.yoosee/history 下载yoosee18版本（一定要18版之前没有分享功能的版本）对你的设备进行配网，配网成功之后查看监控是否正常，正常之后再用你自己的app监控此设备；后期再排查配网哪里有问题

**Comment by AndyJennifer** [comment]
@huangdali  我想问一下，你们给监控设备设置密码走的是哪个接口，我这边配网是没有问题的。因为我通过yoosee添加设备设置密码后，我自己的应用用相同的密码能监控。 意思我这边加密解密是没有问题的。主要的问题是，我这边添加设备的时候，我没有给设备设置上新的密码，
当yoose删除设备时。我这边就提示密码错误了。

**Comment by huangdali** [comment]
```java
 /**
     * 设置设备密码.
     * 用户输入的旧密码：qwe123  新密码为:qaz123
     *
     * @param contactId   设备ID
     * @param oldPassword 旧的数字密码 EntryPassword(qwe123)
     * @param newPassword 新的数字密码 EntryPassword(qaz123)
     * @param RTSPPwd     新的密码(明文) qaz123
     * @param userPwd     新的密码（明文）qaz123
     * @see com.p2p.core.P2PHandler#EntryPassword(String)
     * @see com.p2p.core.P2PInterface.ISetting#vRetSetDevicePasswordResult(int)
     * @see com.p2p.core.P2PInterface.ISetting#ACK_vRetSetDevicePassword(int, int)
     */
    public void setDevicePassword(String contactId, String oldPassword,
                                  String newPassword, String RTSPPwd, String userPwd) {}
```

**Comment by AndyJennifer** [comment]
@huangdali  还是失败。已经要崩溃了O(∩_∩)O哈哈~

**Comment by huangdali** [comment]
估计是你配网哪个步骤有问题；建议您到 http://www.wandoujia.com/apps/com.yoosee/history 下载yoosee18版本（**一定要18版之前没有分享功能的版本**）对你的设备进行配网，配网成功之后查看监控是否正常，正常之后再用你自己的app监控此设备；后期再排查配网哪里有问题

**Comment by AndyJennifer** [comment]
@huangdali 配网没有问题。能连上。我通过自己的app配网，然后调用yoosee（18）添加已连接设备，是可以监控的。我就想知道添加设备这个流程。我到底哪里错了。

**Comment by huangdali** [comment]
https://www.showdoc.cc/web/#/33405883053395?page_id=194454370037718   参考Android SDK集成>设备权限(分享)、同步>设备同步相关目录

**Comment by huangdali** [comment]
一定要看每个接口的“特别说明”

**Comment by AndyJennifer** [comment]
@huangdali  大力哥。看了流程发现，并没有什么用。我在添加设备前调用了 P2PHandler.getInstance().setInitPassword("169", P2PHandler.getInstance().EntryPassword(DEFAULT_DEVICE_PWD), DEFAULT_DEVICE_PWD, DEFAULT_DEVICE_PWD); 然后监控成功了。我的天！原来这个才是设置密码？！

**Comment by huangdali** [comment]
@AndyJennifer 那就是在添加设备的流程上有点问题哦，设置初始化密码（有默认密码的设备才设置）是在配网成功之后调用的(AP配网除外)，
```java
    /**
     * 设置初始密码
     *
     * @param contactId    ip地址末段（eg:192.168.1.34 则contactId=34）
     * @param password     初始密码（密文）
     * @param RTSPPwd      初始密码(明文)
     * @param userPassword 初始密码（明文）
     */
    public void setInitPassword(String contactId, String password,
                                String RTSPPwd, String userPassword) {}
```
